<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Auth\Autentica;
use Phalcon\Tag;
use Util\Infra;

$infra = new Infra();
$auth = new Autentica();
$security_plugin = new SecurityPlugin();
$acl = $security_plugin->getAcl();
$role = $auth->getRoles();
$module = $this->router->getControllerName();

?>

<?= $this->getContent(); ?>

<div class="col-12">
    <?= $this->tag->form(
        [
            "cidade_digital/index",
            "autocomplete" => "off",
            "id" => "formPesquisa"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?= $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="bt_menu_tabela">
                <?= $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
                <button type="button" name="bt_limpar" id="bt_limpar" class="btn btn-warning btn-rounded waves-light w-md" onclick="limpar();">Limpar</button>
                <?php if($acl->isAllowed($role,$module, 'criar')): ?>
                    <button type="button" name="bt_novo" id="bt_novo" class="btn btn-success btn-rounded waves-light w-md" onclick="criar();">Novo</button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?= $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="datatable_listar" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Cidade Digital</th>
                <th>Cidade</th>
                <th>Ativo</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $cidadedigital): ?>
                <?php
                switch($cidadedigital->getAtivo())
                {
                    case '0'://Inativo (False)
                        $ativo = "Inativo";
                        $class_tr = 'class="table-danger"';
                        break;
                    case '1'://Ativo (True)
                        $ativo = "Ativo";
                        $class_tr = null;
                        break;
                }
                ?>
                <tr <?= $class_tr; ?>>
                    <td><?= $cidadedigital->getId() ?></td>
                    <td><?= $cidadedigital->getDescricao() ?></td>
                    <td><?= $cidadedigital->getCidade() ?></td>
                    <td><?= $ativo ?></td>
                    <td class="td_acoes">
                        <?php if($acl->isAllowed($role,$module, 'visualizar')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $cidadedigital->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.png" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                        <?php endif; ?>
                        <?php if($cidadedigital->getAtivo() == '0'): ?>
                            <?php if($acl->isAllowed($role, $module, 'ativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="ativar(<?= $cidadedigital->getId() ?>, '<?= $cidadedigital->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.png" title="Ativar" alt="Ativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($acl->isAllowed($role, $module, 'editar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="editar(<?= $cidadedigital->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.png" title="Editar" alt="Editar" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'inativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="inativar(<?= $cidadedigital->getId() ?>, '<?= $cidadedigital->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.png" title="Desativar" alt="Desativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($acl->isAllowed($role, $module, 'excluir')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="excluir(<?= $cidadedigital->getId() ?>, '<?= $cidadedigital->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.png" title="Excluir" alt="Excluir" height="25" width="25"></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Cadastro -->
<div id="modalCadastro" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalCadastro" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="confirmaCancelar('modalCadastro');">×</button>
                <h5 class="modal-title" id="modalCadastro">Dados da Cidade Digital</h5>
            </div>
            <form id="formCadastro">
                <input type="hidden" id="token" name="<?= $token['tokenKey'] ?>" value="<?= $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a href="#tab_cidade_digital" data-toggle="tab" aria-expanded="true" class="nav-link active" alt="Teste">
                                Cidade Digital
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#tab_conectividade" data-toggle="tab" aria-expanded="false" class="nav-link">
                                Conectividade
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#tab_estacao_telecon" data-toggle="tab" aria-expanded="false" class="nav-link">
                                Estação Telecon
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab_cidade_digital">
                            <div class="form-row">
                                <div class="col-12">
                                    <div class="form-row">
                                        <div class="form-group col-md-4">
                                            <label for="uf_estado">Estado </label>
                                            <?= $this->tag->select(["uf_estado", $estado, "class" => "form-control", "id" => "uf_estado",
                                                "using" => ["uf", "estado",],
                                                "useEmpty" => true,
                                                "emptyText" => "Selecione um Estado",
                                                "emptyValue" => "",
                                                'value' => 'PA']);
                                            ?>
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="lid_cidade">Cidade <span class="required">*</span></label>
                                            <?php echo $this->tag->textField(["lid_cidade", "size" => 120, "class" => "form-control", "id" => "lid_cidade", "placeholder" => "Cidade", "onkeyup" => "autocompletarCidade();"]) ?>
                                            <?php echo $this->tag->hiddenField(["id_cidade", "size" => 120, "class" => "form-control", "id" => "id_cidade"]) ?>
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="descricao">Cidade Digital <span class="required">*</span></label>
                                            <?= $this->tag->textField(["descricao", "size" => 200, "class" => "form-control result", "id" => "descricao", "placeholder" => "Descrição da Cidade Digital"]) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="tab_conectividade">
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <button type="button" name="bt_novo_conectividade" id="bt_novo_conectividade" class="btn btn-success btn-rounded waves-light w-md" onclick="criarComponenteConectividade();">Novo</button>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="hidden_conectividade" style="display: none;">
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label for="id_tipo">Tipo Conectividade <span class="required">*</span></label>
                                            <?= $this->tag->select(["i_id_tipo", $tipocd, "class" => "form-control concat", "id" => "i_id_tipo",
                                                "using" => ["id", "descricao",],
                                                "useEmpty" => true,
                                                "emptyText" => "Selecione um tipo",
                                                "emptyValue" => ""])
                                            ?>
                                        </div>
                                        <div class="form-group col-md-6">
                                            <label for="descricao">Conectividade <span class="required">*</span></label>
                                            <?= $this->tag->textField(["i_descricao", "size" => 200, "class" => "form-control result", "id" => "i_descricao", "placeholder" => "Descrição da Conectividade"]) ?>
                                        </div>
                                        <div class="form-group col-md-9">
                                            <label for="endereco">Endereço da Conectividade</label>
                                            <?= $this->tag->textField(["i_endereco", "size" => 200, "class" => "form-control", "id" => "i_endereco", "placeholder" => "Endereço da Conectividade"]) ?>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <button id="bt_inserir_conectividade" name="bt_inserir_conectividade" type="button" class="btn btn-sucess btn-rounded waves-light w-sm bt_menu_tabela" onclick="inserirComponenteConectividade();">Inserir</button>
                                            <button type="button" name="bt_cancelar_conectividade" id="bt_cancelar_conectividade" class="btn btn-danger btn-rounded waves-light w-sm bt_menu_tabela" onclick="cancelarComponenteConectividade();">Cancelar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <table id="tabela_conectividade" class="table table-hover" style="display: none;">
                                    <thead>
                                    <tr>
                                        <th>Tipo</th>
                                        <th>Conectividade</th>
                                        <th>Endereço</th>
                                        <th>Excluir?</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="tab_estacao_telecon">
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <button type="button" name="bt_novo_estacaotelecon" id="bt_novo_estacaotelecon" class="btn btn-success btn-rounded waves-light w-md" onclick="criarComponenteETelecon();">Novo</button>
                                </div>
                            </div>
                            <div class="form-row hidden_estacaotelecon" style="display: none;">
                                <div class="form-row">
                                    <div class="form-group col-md-3">
                                        <label for="i_descricao_et">Descrição <span class="required">*</span></label>
                                        <?= $this->tag->textField(["i_descricao_et", "size" => 200, "class" => "form-control", "id" => "i_descricao_et", "placeholder" => "Descrição da Estação Telecon"]) ?>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="lid_contrato">Contrato </label>
                                        <?php echo $this->tag->textField(["lid_contrato", "size" => 120, "class" => "form-control", "id" => "lid_contrato", "placeholder" => "Contrato", "onkeyup" => "autocompletarContrato();"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_contrato", "size" => 120, "class" => "form-control", "id" => "i_id_contrato"]) ?>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="lterreno">Terreno <span class="required">*</span></label>
                                        <?php echo $this->tag->textField(["lid_terreno", "size" => 120, "class" => "form-control", "id" => "lid_terreno", "placeholder" => "Terreno", "onkeyup" => "autocompletarTerreno();"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_terreno", "size" => 120, "class" => "form-control", "id" => "i_id_terreno"]) ?>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="ltorre">Torre <span class="required">*</span></label>
                                        <?php echo $this->tag->textField(["lid_torre", "size" => 120, "class" => "form-control", "id" => "lid_torre", "placeholder" => "Torre", "onkeyup" => "autocompletarTorre();"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_torre", "size" => 120, "class" => "form-control", "id" => "i_id_torre"]) ?>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-3">
                                        <label for="lid_set_equipamento">Set de Equipamento <span class="required">*</span></label>
                                        <?php echo $this->tag->textField(["lid_set_equipamento", "size" => 120, "class" => "form-control", "id" => "lid_set_equipamento", "placeholder" => "Set de Equipamento", "onkeyup" => "autocompletarSetEquipamento();"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_set_equipamento", "size" => 120, "class" => "form-control", "id" => "i_id_set_equipamento"]) ?>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="lid_set_seguranca">Set de Segurança </label>
                                        <?php echo $this->tag->textField(["lid_set_seguranca", "size" => 120, "class" => "form-control", "id" => "lid_set_seguranca", "placeholder" => "Set de Segurança", "onkeyup" => "autocompletarSetSeguranca();"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_set_seguranca", "size" => 120, "class" => "form-control", "id" => "i_id_set_seguranca"]) ?>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="lid_unidade_consumidora">Unidade Consumidora </label>
                                        <?php echo $this->tag->textField(["lid_unidade_consumidora", "size" => 120, "class" => "form-control", "id" => "lid_unidade_consumidora", "placeholder" => "Unidade Consumidora", "onkeyup" => "autocompletarUnidadeConsumidora();"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_unidade_consumidora", "size" => 120, "class" => "form-control", "id" => "i_id_unidade_consumidora"]) ?>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <button id="bt_inserir_estacaotelecon" name="bt_inserir_estacaotelecon" type="button" class="btn btn-sucess btn-rounded waves-light w-sm bt_menu_tabela" onclick="inserirComponenteETelecon();">Inserir</button>
                                        <button type="button" name="bt_cancelar_estacaotelecon" id="bt_cancelar_estacaotelecon" class="btn btn-danger btn-rounded waves-light w-sm bt_menu_tabela" onclick="cancelarComponenteETelecon();">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <table id="tabela_estacaotelecon" class="table table-hover" style="display: none;">
                                    <thead>
                                    <tr>
                                        <th>Descrição</th>
                                        <th>Terreno</th>
                                        <th>Torre</th>
                                        <th>Set Equipamento</th>
                                        <th>Excluir?</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="confirmaCancelar('modalCadastro');">Fechar</button>
                        <button id="salvarCadastro" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light" onclick="salvar();" value="">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->