<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Phalcon\Tag;

?>

<?php echo $this->getContent(); ?>

<!--<div class="col-12">-->
<!--    --><?php
//    echo $this->tag->form(
//        [
//            "cidade_digital/localizar",
//            "autocomplete" => "off"
//        ]
//    );
//    ?>
<!--    <div class="form-row">-->
<!--        <div class="form-group col-md-2">-->
<!--            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>-->
<!--            <div class="col-sm-10">-->
<!--                --><?php //echo $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
<!--            </div>-->
<!--        </div>-->
<!--        <div class="form-group col-md-2">-->
<!--            <div class="bt_menu_tabela">-->
<!--                --><?php //echo $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    --><?php //echo $this->tag->endForm(); ?>
<!--</div>-->

<div class="col-12">
    <div id="loader_mapa" style="text-align: center;"></div>
    <div id="mapa"></div>
</div>