<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

?>

<?php echo $this->getContent(); ?>

<div class="col-12">
    <?php
    echo $this->tag->form(
        [
            "lov",
            "autocomplete" => "off",
            "id" => "formPesquisa"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <div class="bt_menu_tabela">
                <?php echo $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
            </div>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="tb_lov" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Tipo</th>
                <th>Descrição</th>
                <th>Código Específico</th>
                <th>Valor</th>
                <th>Duração</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $lov): ?>
                <?php
                switch($lov->tipo){
                    case '1':
                        $lovtipo = "Tipo de Unidade";
                        break;
                    case '2':
                        $lovtipo = "Usa Contrato";
                        break;
                    case '3':
                        $lovtipo = "Função";
                        break;
                    case '4':
                        $lovtipo = "Esfera";
                        break;
                    case '5':
                        $lovtipo = "Setor";
                        break;
                    case '6':
                        $lovtipo = "Status";
                        break;
                    case '7':
                        $lovtipo = "Enlace";
                        break;
                    case '8':
                        $lovtipo = "Tipo Email";
                        break;
                    case '9':
                        $lovtipo = "Tipo de Cliente (PF/PJ)";
                        break;
                    case '10':
                        $lovtipo = "Sexo";
                        break;
                    case '11':
                        $lovtipo = "Tipo de Endereço";
                        break;
                    case '12':
                        $lovtipo = "Tipo de Telefone";
                        break;
                    case '13':
                        $lovtipo = "Tipo de Contato (Cargo Empresa)";
                        break;
                    case '14':
                        $lovtipo = "Cluster";
                        break;
                    case '15':
                        $lovtipo = "Tipo de Equipamento";
                        break;
                    case '16':
                        $lovtipo = "Tipo de Movimento";
                        break;
                    case '17':
                        $lovtipo = "Tipo de Banda";
                        break;
                    case '18':
                        $lovtipo = "Tipo de Conectividade";
                        break;
                    case '19':
                        $lovtipo = "Tipo de Link";
                        break;
                    case '20':
                        $lovtipo = "Tipo de Anexo";
                        break;
                    case '21':
                        $lovtipo = "Tipo de Componente de Set de Segurança";
                        break;
                    case '22':
                        $lovtipo = "Tipo de Torre";
                        break;
                    case '23':
                        $lovtipo = "Tipo de Proposta";
                        break;
                    case '26':
                        $lovtipo = "Tipo de Contrato";
                        break;
                    case '27':
                        $lovtipo = "Tipo de Processo de Contratação";
                        break;
                    case '29':
                        $lovtipo = "Tipo de Modalidade de Contratação de Garantia";
                        break;
                    case '31':
                        $lovtipo = "Tipo de Fiscal de Contrato";
                        break;
                    case '32':
                        $lovtipo = "Tipo de Estação Telecom";
                        break;
                }
                ?>
                <tr>
                    <td><?php echo $lov->id ?></td>
                    <td><?php echo $lovtipo ?></td>
                    <td><?php echo $lov->descricao ?></td>
                    <td><?php echo $lov->codigoespecifico ?></td>
                    <td><?php echo $lov->valor ?></td>
                    <td><?php echo $lov->duracao ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Lov -->
<div id="modallov" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modallov" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modallov">Dados a serem Cadastrados</h5>
            </div>
            <form id="formLov">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="tipo">Tipo de Registro <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["tipo", $tipos_lov, "class" => "form-control", "id" => "tipo",
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um tipo",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="descricao">Descrição <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["descricao", "size" => 200, "class" => "form-control", "id" => "descricao", "placeholder" => "Descricao"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="codigoespecifico">Código Específico</label>
                                    <?php echo $this->tag->textField(["codigoespecifico", "size" => 60, "class" => "form-control", "id" => "codigoespecifico", "placeholder" => "Código Específico"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="valor">Valor</label>
                                    <?php echo $this->tag->textField(["valor", "size" => 60, "class" => "form-control", "id" => "valor", "placeholder" => "Valor"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="duracao">Duração</label>
                                    <?php echo $this->tag->timeField(["duracao", "size" => 60, "class" => "form-control", "id" => "duracao", "placeholder" => "Duração"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" data-dismiss="modal">Fechar</button>
                        <button id="salvarLov" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->