<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search lov
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["lov/new", "Create lov"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "lov/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTipo" class="col-sm-2 control-label">Tipo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["tipo", "type" => "number", "class" => "form-control", "id" => "fieldTipo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescricao" class="col-sm-2 control-label">Descricao</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["descricao", "size" => 30, "class" => "form-control", "id" => "fieldDescricao"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCodigoespecifico" class="col-sm-2 control-label">Codigoespecifico</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["codigoespecifico", "size" => 30, "class" => "form-control", "id" => "fieldCodigoespecifico"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldValor" class="col-sm-2 control-label">Valor</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["valor", "size" => 30, "class" => "form-control", "id" => "fieldValor"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDuracao" class="col-sm-2 control-label">Duracao</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["duracao", "size" => 30, "class" => "form-control", "id" => "fieldDuracao"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
