<div class="col-12">
    <div class="card-box">
        <table id="tb_lov" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Tipo</th>
                    <th>Descricao</th>
                    <th>Código Específico</th>
                    <th>Valor</th>
                    <th>Duração</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $lov): ?>
            <?php                
                switch($lov->tipo){
                    case '1':
                    $lovtipo = "Tipo Unidade";
                    break;
                    case '2':
                    $lovtipo = "Usa Contrato";
                    break;
                    case '3':
                    $lovtipo = "Função";
                    break;
                    case '4':
                    $lovtipo = "Esfera";
                    break;
                    case '5':
                    $lovtipo = "Setor";
                    break;
                    case '6':
                    $lovtipo = "Status";
                    break;
                    case '7':
                    $lovtipo = "Enlace";
                    break;
                    case '8':
                    $lovtipo = "Tipo Email";
                    break;
                    case '9':
                    $lovtipo = "Tipo Cliente (PF/PJ)";
                    break;
                    case '10':
                    $lovtipo = "Tipo Status Movimento";
                    break;
                }
            ?>
                    <tr>
                        <td><?php echo $lov->id ?></td>
                        <td><?php echo $lovtipo ?></td>
                        <td><?php echo $lov->descricao ?></td>
                        <td><?php echo $lov->codigoespecifico ?></td>
                        <td><?php echo $lov->valor ?></td>
                        <td><?php echo $lov->duracao ?></td>
                    </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Lov -->
<div id="modallov" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modallov" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modallov">Dados a serem Cadastrados</h5>
            </div>
            <form id="formLov">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <?php echo $this->tag->select(["tipo", $tipos_lov, "class" => "form-control", "id" => "tipo",
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um tipo",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <?php echo $this->tag->textField(["descricao", "size" => 200, "class" => "form-control", "id" => "descricao", "placeholder" => "Descricao"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <?php echo $this->tag->textField(["codigoespecifico", "size" => 60, "class" => "form-control", "id" => "codigoespecifico", "placeholder" => "Código Específico"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <?php echo $this->tag->textField(["valor", "size" => 60, "class" => "form-control", "id" => "valor", "placeholder" => "Valor"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <?php echo $this->tag->timeField(["duracao", "size" => 60, "class" => "form-control", "id" => "duracao", "placeholder" => "Duração"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                    <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" data-dismiss="modal">Fechar</button>
                    <button id="salvarLov" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->