<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["usuario", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit usuario
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "usuario/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdPessoa" class="col-sm-2 control-label">Id Of Pessoa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_pessoa", "type" => "number", "class" => "form-control", "id" => "fieldIdPessoa"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRolesName" class="col-sm-2 control-label">Roles Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["roles_name", "size" => 30, "class" => "form-control", "id" => "fieldRolesName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLogin" class="col-sm-2 control-label">Login</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["login", "size" => 30, "class" => "form-control", "id" => "fieldLogin"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSenha" class="col-sm-2 control-label">Senha</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["senha", "size" => 30, "class" => "form-control", "id" => "fieldSenha"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
