<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Phalcon\Tag;
use Util\Util;

?>

<?php echo $this->getContent(); ?>

<div class="col-12">
    <?php
    echo $this->tag->form(
        [
            "usuario/index",
            "autocomplete" => "off"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldLogin" class="col-sm-2 control-label">Login</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["login", "size" => 30, "class" => "form-control", "id" => "fieldLogin"]) ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <label for="fieldIdCliente" class="col-sm-2 control-label">Perfil</label>
            <div class="col-sm-10">
                <?php echo $this->tag->select(["roles_name", $roles, "class" => "form-control", "id" => "fieldRolesName",
                    "using" => ["name", "name",],
                    "useEmpty" => true,
                    "emptyText" => "Selecione um Perfil",
                    "emptyValue" => ""])
                ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <div class="bt_menu_tabela">
                <?php echo $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
            </div>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="tb_usuario" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Perfil</th>
                    <th>Login</th>
                    <th>Data Cadastro</th>
                    <th>Data Alteração</th>
                    <th>Data Último Acesso</th>
                    <th>Ativo</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $usuario): ?>
            <?php
            
            $util = new Util();
                
                switch($usuario->primeiroacesso){
                    case '0'://Não Acessou (False)
                    $primeiroacesso = "Não";
                    break;
                    case '1'://Acessou (True)
                    $primeiroacesso = "Sim";
                    break;
                }
                switch($usuario->Pessoa->ativo){
                    case '0'://Inativo (False)
                    $ativo = "Inativo";
                    break;
                    case '1'://Ativo (True)
                    $ativo = "Ativo";
                    break;
                }
            ?>
                    <tr>
                        <td><?php echo $usuario->id ?></td>
                        <td><?php echo $usuario->Pessoa->nome ?></td>
                        <td><?php echo $usuario->Pessoa->PessoaEmail[0]->email ?></td>
                        <td><?php echo $usuario->roles_name ?></td>
                        <td><?php echo $usuario->login ?></td>
                        <td><?php echo $util->converterDataHoraParaBr($usuario->Pessoa->create_at) ?></td>
                        <td><?php echo $util->converterDataHoraParaBr($usuario->Pessoa->update_at) ?></td>
                        <td><?php echo $util->converterDataHoraParaBr($usuario->data_ultimoacesso) ?></td>
                        <td><?php echo $ativo ?></td>
                    </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Usuário -->
<div id="modalusuario" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalusuario" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalusuario">Dados do Usuário</h5>
            </div>
            <form id="formUser">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="nome_pessoa">Nome <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["nome_pessoa", "size" => 120, "class" => "form-control", "id" => "nome_pessoa", "placeholder" => "Nome"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="size">Login <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["login", "size" => 80, "class" => "form-control", "id" => "login", "placeholder" => "Login"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="email">E-mail <span class="required">*</span></label>
                                    <?php echo $this->tag->emailField(["email", "size" => 120, "class" => "form-control", "id" => "email", "placeholder" => "E-mail"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="roles_name">Perfil <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["roles_name", $roles, "class" => "form-control", "id" => "roles_name",
                                        "using" => ["name", "name",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um perfil",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row" id="reset_senha" style="display: none">
                                <div class="form-group col-md-6">
                                    <label for="senha_reset">Resetar a senha do Usuário?</label>
                                    <button id="senha_reset" name="senha_reset" type="button" class="btn btn-danger btn-rounded waves-light waves-effect w-md">Resetar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" data-dismiss="modal">Fechar</button>
                        <button id="salvaUser" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->