<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Circuitos - Sistema de Gestão de Circuitos do Navega Pará</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="<?= DIR_STATICS ?>public/images/favicon.ico">

    <!-- App css -->
    <link href="<?= DIR_STATICS ?>public/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="<?= DIR_STATICS ?>public/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="<?= DIR_STATICS ?>public/css/metismenu.min.css" rel="stylesheet" type="text/css" />
    <link href="<?= DIR_STATICS ?>public/css/style.css" rel="stylesheet" type="text/css" />

    <!-- Sweet Alert css -->
    <link href="<?= DIR_STATICS ?>public/plugins/sweet-alert/sweetalert2.min.css" rel="stylesheet" type="text/css" />

    <script src="<?= DIR_STATICS ?>public/js/modernizr.min.js"></script>

</head>


<body class="bg-accpunt-pages">

<!-- HOME -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">

                <div class="wrapper-page">

                    <div class="account-pages">
                        <div class="account-box">
                            <div class="account-logo-box">
                                <h2 class="text-uppercase text-center">
                                    <a href="http://www.prodepa.pa.gov.br" class="text-success">
                                        <span><img src="<?= DIR_STATICS ?>public/images/logo_dark.png" alt="" height="120"></span>
                                    </a>
                                </h2>
                                <h6 class="text-uppercase text-center font-bold mt-4">Primeiro Acesso</h6>
                            </div>
                            <div class="account-content">

                                <?php echo $this->getContent(); ?>

                                <?php
                                echo $this->tag->form(
                                    [
                                        "usuario/primeiro",
                                        "autocomplete" => "off",
                                        "class" => "form-horizontal"
                                    ]
                                );
                                ?>
                                <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
                                <div class="form-group row m-b-20">
                                    <div class="col-12">
                                        <label for="username">Seu nome</label>
                                        <input disabled class="form-control" type="username" id="username" value="<?php echo $nome ?>">
                                    </div>
                                </div>
                                <div class="form-group row m-b-20">
                                    <div class="col-12">
                                        <label for="password">Nova Senha</label>
                                        <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "password", "placeholder" => "Nova senha"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row m-b-20">
                                    <div class="col-12">
                                        <label for="password2">Confirmar Senha</label>
                                        <?php echo $this->tag->passwordField(["password2", "size" => 30, "class" => "form-control", "id" => "password2", "placeholder" => "Confirmar Senha"]) ?>
                                    </div>
                                </div>
                                <div class="form-group row text-center m-t-10">
                                    <div class="col-12">
                                        <?php echo $this->tag->submitButton(["Confirmar", "class" => "btn btn-block btn-gradient"]) ?>
                                        <!--                                        <button name="btnTrocarPrimeira" id="btnTrocarPrimeira" class="btn btn-block btn-gradient" type="button" onclick="confirmarPrimeiraTroca();">Confirmar</button>-->
                                    </div>
                                </div>

                                <?php echo $this->tag->endForm(); ?>

                            </div>
                        </div>
                    </div>
                    <!-- end card-box-->


                </div>
                <!-- end wrapper -->

            </div>
        </div>
    </div>
</section>
<!-- END HOME -->


<!-- jQuery  -->
<script src="<?= DIR_STATICS ?>public/js/jquery.min.js"></script>
<script src="<?= DIR_STATICS ?>public/js/popper.min.js"></script>
<script src="<?= DIR_STATICS ?>public/js/bootstrap.min.js"></script>
<script src="<?= DIR_STATICS ?>public/js/metisMenu.min.js"></script>
<script src="<?= DIR_STATICS ?>public/js/waves.js"></script>
<script src="<?= DIR_STATICS ?>public/js/jquery.slimscroll.js"></script>

<!-- Sweet Alert Js  -->
<script src="<?= DIR_STATICS ?>public/plugins/sweet-alert/sweetalert2.min.js" type="text/javascript"></script>
<script src="<?= DIR_STATICS ?>public/plugins/switchery/switchery.min.js" type="text/javascript"></script>

<!-- App js -->
<script src="<?= DIR_STATICS ?>public/js/jquery.core.js"></script>
<script src="<?= DIR_STATICS ?>public/js/jquery.app.js"></script>

<!-- Scripts Específicos da Página -->
<!--<script type="application/javascript">-->
<!--    function confirmarPrimeiraTroca()-->
<!--    {-->
<!--        swal("Confirmado!");-->
<!--    }-->
<!--</script>-->

</body>
</html>