<div class="account-content">
<?php echo $this->getContent(); ?>
    <?php
        echo $this->tag->form(
            [
                "usuario/trocar",
                "autocomplete" => "off",
                "class" => "form-horizontal"
            ]
        );
    ?>
        <input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>
        <div class="form-group row m-b-20">
            <div class="col-12">
                <label for="username">Seu nome</label>
                <input disabled class="form-control" type="username" id="username" value="<?php echo $nome ?>">
            </div>
        </div>
        <div class="form-group row m-b-20">
            <div class="col-12">
                <label for="password">Nova Senha</label>
                <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "password", "placeholder" => "Nova senha"]) ?>
            </div>
        </div>
        <div class="form-group row m-b-20">
            <div class="col-12">
                <label for="password2">Confirmar Senha</label>
                <?php echo $this->tag->passwordField(["password2", "size" => 30, "class" => "form-control", "id" => "password2", "placeholder" => "Confirmar Senha"]) ?>
            </div>
        </div>
        <div class="form-group row text-center m-t-10">
            <div class="col-12">
                <?php echo $this->tag->submitButton(["Confirmar", "class" => "btn btn-block btn-gradient"]) ?>
            </div>
        </div>
    </form>
</div>