<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Auth\Autentica;
use Phalcon\Tag;
use Util\Infra;

$infra = new Infra();
$auth = new Autentica();
$security_plugin = new SecurityPlugin();
$acl = $security_plugin->getAcl();
$role = $auth->getRoles();
$module = $this->router->getControllerName();

?>

<?= $this->getContent(); ?>

<div class="col-12">
    <?= $this->tag->form(
        [
            "proposta_comercial/index",
            "autocomplete" => "off",
            "id" => "formPesquisa"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?= $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="bt_menu_tabela">
                <?= $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
                <button type="button" name="bt_limpar" id="bt_limpar" class="btn btn-warning btn-rounded waves-light w-md" onclick="limpar();">Limpar</button>
                <?php if($acl->isAllowed($role,$module, 'criar')): ?>
                    <button type="button" name="bt_novo" id="bt_novo" class="btn btn-success btn-rounded waves-light w-md" onclick="criar();">Novo</button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?= $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="datatable_listar" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Número</th>
                <th>Cliente</th>
                <th>Localizacao</th>
                <th>Status</th>
                <th>Data Proposta</th>
                <th>Data Vencimento</th>
                <th>Ativo</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page as $proposta_comercial): ?>
                <?php
                switch($proposta_comercial->getAtivo())
                {
                    case '0'://Inativo (False)
                        $ativo = "Inativo";
                        $class_tr = 'class="table-danger"';
                        break;
                    case '1'://Ativo (True)
                        $ativo = "Ativo";
                        $class_tr = null;
                        break;
                }
                ?>
                <tr <?= $class_tr; ?>>
                    <td><?= $proposta_comercial->getId() ?></td>
                    <td><?= $proposta_comercial->getNumero() ?></td>
                    <td><?= $proposta_comercial->getCliente() ?></td>
                    <td><?= $proposta_comercial->getLocalizacao() ?></td>
                    <td><?= $proposta_comercial->getStatus() ?></td>
                    <td><?= $proposta_comercial->getDataProposta() ?></td>
                    <td><?= $proposta_comercial->getDataVencimento() ?></td>
                    <td><?= $ativo ?></td>
                    <td class="td_acoes">
                        <?php if($acl->isAllowed($role,$module, 'visualizar')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $proposta_comercial->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.png" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                        <?php endif; ?>
                        <?php if($proposta_comercial->getAtivo() == '0'): ?>
                            <?php if($acl->isAllowed($role, $module, 'ativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="ativar(<?= $proposta_comercial->getId() ?>, '<?= $proposta_comercial->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.png" title="Ativar" alt="Ativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($acl->isAllowed($role, $module, 'editar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="editar(<?= $proposta_comercial->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.png" title="Editar" alt="Editar" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'inativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="inativar(<?= $proposta_comercial->getId() ?>, '<?= $proposta_comercial->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.png" title="Desativar" alt="Desativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($acl->isAllowed($role, $module, 'excluir')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="excluir(<?= $proposta_comercial->getId() ?>, '<?= $proposta_comercial->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.png" title="Excluir" alt="Excluir" height="25" width="25"></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Cadastro -->
<div id="modalCadastro" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalCadastro" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="confirmaCancelar('modalCadastro');">×</button>
                <h5 class="modal-title" id="modalCadastro">Dados da Proposta Comercial</h5>
            </div>
            <form id="formCadastro">
                <input type="hidden" id="token" name="<?= $token['tokenKey'] ?>" value="<?= $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a href="#tab_proposta_comercial" data-toggle="tab" aria-expanded="true" class="nav-link active">
                                Proposta Comercial
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#tab_objetivos_proposta_comercial" data-toggle="tab" aria-expanded="false" class="nav-link">
                                Objetivos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#tab_condicoes_proposta_comercial" data-toggle="tab" aria-expanded="false" class="nav-link">
                                Condições
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#tab_itens_proposta_comercial" data-toggle="tab" aria-expanded="false" class="nav-link">
                                Itens da Proposta
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab_proposta_comercial">
                            <div class="form-row">
                                <div class="col-12">
                                    <div class="form-row">
                                        <div class="form-group col-md-4">
                                            <label for="lid_cliente">Cliente <span class="required">*</span></label>
                                            <?php echo $this->tag->textField(["lid_cliente", "size" => 120, "class" => "form-control", "id" => "lid_cliente", "placeholder" => "Cliente", "onkeyup" => "autocompletarCliente();"]) ?>
                                            <?php echo $this->tag->hiddenField(["id_cliente", "size" => 120, "class" => "form-control", "id" => "id_cliente"]) ?>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="id_tipo_proposta">Tipo de Proposta <span class="required">*</span></label>
                                            <?php echo $this->tag->select(["id_tipo_proposta", $tipos, "class" => "form-control", "id" => "id_tipo_proposta",
                                                "using" => ["id", "descricao",],
                                                "useEmpty" => true,
                                                "emptyText" => "Selecione o tipo de Proposta",
                                                "emptyValue" => ""])
                                            ?>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="id_localizacao">Localização <span class="required">*</span></label>
                                            <?php echo $this->tag->select(["id_localizacao", $tipos, "class" => "form-control", "id" => "id_localizacao",
                                                "using" => ["id", "descricao",],
                                                "useEmpty" => true,
                                                "emptyText" => "Selecione a Localização",
                                                "emptyValue" => ""])
                                            ?>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="data_proposta">Data da Proposta <span class="required">*</span></label>
                                            <?= $this->tag->textField(["data_proposta", "size" => 200, "class" => "form-control data", "id" => "data_proposta", "placeholder" => "Data da Proposta"]) ?>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="numero">Número <span class="required">*</span></label>
                                            <?= $this->tag->textField(["numero", "size" => 200, "class" => "form-control", "id" => "numero", "placeholder" => "Número da Proposta"]) ?>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-2">
                                            <label for="vencimento">Vencimento <span class="required">*</span></label>
                                            <?= $this->tag->textField(["vencimento", "size" => 200, "class" => "form-control data", "id" => "vencimento", "placeholder" => "Vencimento da Proposta"]) ?>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="reajuste">Reajuste <span class="required">*</span></label>
                                            <?= $this->tag->textField(["reajuste", "size" => 200, "class" => "form-control valor_percentual", "id" => "reajuste", "placeholder" => "Reajuste da Proposta"]) ?>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="desconto">Desconto <span class="required">*</span></label>
                                            <?= $this->tag->textField(["desconto", "size" => 200, "class" => "form-control valor_percentual", "id" => "desconto", "placeholder" => "Desconto da Proposta"]) ?>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="imposto">Imposto <span class="required">*</span></label>
                                            <?= $this->tag->textField(["imposto", "size" => 200, "class" => "form-control valor_percentual", "id" => "imposto", "placeholder" => "Imposto da Proposta"]) ?>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="encargos">Encargos <span class="required">*</span></label>
                                            <?= $this->tag->textField(["encargos", "size" => 200, "class" => "form-control valor_percentual", "id" => "encargos", "placeholder" => "Encargos da Proposta"]) ?>
                                        </div>
                                        <div class="form-group col-md-2">
                                            <label for="valor_global">Valor Global <span class="required">*</span></label>
                                            <?= $this->tag->textField(["valor_global", "size" => 200, "class" => "form-control valor_monetario_limpo", "id" => "valor_global", "placeholder" => "Valor Global da Proposta"]) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="tab_objetivos_proposta_comercial">
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="objetivo">Objetivo</label>
                                    <?php echo $this->tag->textArea(["objetivo", "size" => 500, "class" => "form-control", "id" => "objetivo", "placeholder" => "Objetivo da Proposta"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="objetivo_especifico">Objetivo Específico</label>
                                    <?php echo $this->tag->textArea(["objetivo_especifico", "size" => 500, "class" => "form-control", "id" => "objetivo_especifico", "placeholder" => "Objetivo Específico da Proposta"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="objetivo">Descritivo</label>
                                    <?php echo $this->tag->textArea(["objetivo", "size" => 500, "class" => "form-control", "id" => "objetivo", "placeholder" => "Objetivo da Proposta"]) ?>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="tab_condicoes_proposta_comercial">
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="responsabilidade">Responsabilidade</label>
                                    <?php echo $this->tag->textArea(["responsabilidade", "size" => 500, "class" => "form-control", "id" => "responsabilidade", "placeholder" => "Responsabilidade da Proposta"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="condicoes_pgto">Condições de Pagamento</label>
                                    <?php echo $this->tag->textArea(["condicoes_pgto", "size" => 500, "class" => "form-control", "id" => "condicoes_pgto", "placeholder" => "Condições de Pagamento da Proposta"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="prazo_execucao">Prazo de Execução</label>
                                    <?php echo $this->tag->textArea(["prazo_execucao", "size" => 500, "class" => "form-control", "id" => "prazo_execucao", "placeholder" => "Prazo de Execução da Proposta"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="consideracoes">Considerações</label>
                                    <?php echo $this->tag->textArea(["consideracoes", "size" => 500, "class" => "form-control", "id" => "consideracoes", "placeholder" => "Considerações da Proposta"]) ?>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="tab_itens_proposta_comercial">

                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="confirmaCancelar('modalCadastro');">Fechar</button>
                        <button id="salvarCadastro" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light" onclick="salvar();" value="">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->