<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["cliente", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit cliente
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "cliente/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldIdPessoa" class="col-sm-2 control-label">Id Of Pessoa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_pessoa", "type" => "number", "class" => "form-control", "id" => "fieldIdPessoa"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdTipocliente" class="col-sm-2 control-label">Id Of Tipocliente</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_tipocliente", "type" => "number", "class" => "form-control", "id" => "fieldIdTipocliente"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
