<?php

use Util\Util;

?>

<div class="col-12">
    <div class="card-box">
        <table id="tb_cliente" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Tipo</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Perfil</th>
                    <th>Login</th>
                    <th>Data Cadastro</th>
                    <th>Data Alteração</th>
                    <th>Ativo</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $cliente): ?>
            <?php            
                $util = new Util();
                
                switch($cliente->primeiroacesso){
                    case '0'://Não Acessou (False)
                    $primeiroacesso = "Não";
                    break;
                    case '1'://Acessou (True)
                    $primeiroacesso = "Sim";
                    break;
                }
                switch($cliente->Pessoa->ativo){
                    case '0'://Inativo (False)
                    $ativo = "Inativo";
                    break;
                    case '1'://Ativo (True)
                    $ativo = "Ativo";
                    break;
                }
            ?>
                    <tr>
                        <td><?php echo $cliente->id ?></td>
                        <td><?php echo $cliente->Pessoa->nome ?></td>
                        <td><?php echo $cliente->Pessoa->PessoaEmail[0]->email ?></td>
                        <td><?php echo $cliente->roles_name ?></td>
                        <td><?php echo $cliente->login ?></td>
                        <td><?php echo $util->converterDataHoraParaBr($cliente->Pessoa->create_at) ?></td>
                        <td><?php echo $util->converterDataHoraParaBr($cliente->Pessoa->update_at) ?></td>
                        <td><?php echo $util->converterDataHoraParaBr($cliente->data_ultimoacesso) ?></td>
                        <td><?php echo $ativo ?></td>
                    </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Cliente -->
<div id="modalcliente" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalcliente" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalcliente">Dados do Cliente</h5>
            </div>
            <form id="formCliente">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <?php echo $this->tag->textField(["nome_pessoa", "size" => 30, "class" => "form-control", "id" => "nome_pessoa", "placeholder" => "Nome"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <?php echo $this->tag->textField(["login", "size" => 30, "class" => "form-control", "id" => "login", "placeholder" => "Login"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <?php echo $this->tag->emailField(["email", "size" => 120, "class" => "form-control", "id" => "email", "placeholder" => "E-mail"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <?php echo $this->tag->select(["roles_name", ["teste" => "Teste"], "class" => "form-control", "id" => "roles_name",
                                        "using" => ["name", "name",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um perfil",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row" id="reset_senha" style="display: none">
                                <div class="form-group col-md-6">
                                    <label for="senha_reset">Resetar a senha do Cliente?</label>
                                    <button id="senha_reset" name="senha_reset" type="button" class="btn btn-danger btn-rounded waves-light waves-effect w-md">Resetar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                    <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" data-dismiss="modal">Fechar</button>
                    <button id="salvaCliente" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->