<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Auth\Autentica;
use Phalcon\Tag;
use Util\Infra;

$infra = new Infra();
$auth = new Autentica();
$security_plugin = new SecurityPlugin();
$acl = $security_plugin->getAcl();
$role = $auth->getRoles();
$module = $this->router->getControllerName();

?>

<?= $this->getContent(); ?>

<div class="col-12">
    <?= $this->tag->form(
        [
            "terreno/index",
            "autocomplete" => "off",
            "id" => "formPesquisa"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?= $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="bt_menu_tabela">
                <?= $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
                <button type="button" name="bt_limpar" id="bt_limpar" class="btn btn-warning btn-rounded waves-light w-md" onclick="limpar();">Limpar</button>
                <?php if($acl->isAllowed($role,$module, 'criar')): ?>
                    <button type="button" name="bt_novo" id="bt_novo" class="btn btn-success btn-rounded waves-light w-md" onclick="criar();">Novo</button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?= $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="datatable_listar" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Descrição</th>
                <th>Propriedade PRODEPA</th>
                <th>Fornecedor</th>
                <th>Cidade</th>
                <th>Ativo</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page as $terreno): ?>
                <?php
                switch($terreno->getAtivo())
                {
                    case '0'://Inativo (False)
                        $ativo = "Inativo";
                        $class_tr = 'class="table-danger"';
                        break;
                    case '1'://Ativo (True)
                        $ativo = "Ativo";
                        $class_tr = null;
                        break;
                }
                $propriedade_prodepa = ($terreno->getPropriedadeProdepa()) ? 'Sim' : 'Não';
                ?>
                <tr <?= $class_tr; ?>>
                    <td><?= $terreno->getId() ?></td>
                    <td><?= $terreno->getDescricao() ?></td>
                    <td><?= $propriedade_prodepa ?></td>
                    <td><?= $terreno->getFornecedor() ?></td>
                    <td><?= $terreno->getCidade() ?></td>
                    <td><?= $ativo ?></td>
                    <td class="td_acoes">
                        <?php if($acl->isAllowed($role,$module, 'visualizar')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $terreno->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.png" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                        <?php endif; ?>
                        <?php if($terreno->getAtivo() == '0'): ?>
                            <?php if($acl->isAllowed($role, $module, 'ativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="ativar(<?= $terreno->getId() ?>, '<?= $terreno->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.png" title="Ativar" alt="Ativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($acl->isAllowed($role, $module, 'editar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="editar(<?= $terreno->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.png" title="Editar" alt="Editar" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'inativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="inativar(<?= $terreno->getId() ?>, '<?= $terreno->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.png" title="Desativar" alt="Desativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($acl->isAllowed($role, $module, 'excluir')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="excluir(<?= $terreno->getId() ?>, '<?= $terreno->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.png" title="Excluir" alt="Excluir" height="25" width="25"></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Cadastro -->
<div id="modalCadastro" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalCadastro" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="confirmaCancelar('modalCadastro');">×</button>
                <h5 class="modal-title" id="modalCadastro">Dados do Terreno</h5>
            </div>
            <form id="formCadastro">
                <input type="hidden" id="token" name="<?= $token['tokenKey'] ?>" value="<?= $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="propriedade_prodepa">Propriedade PRODEPA? <span class="required">*</span></label>
                                    <select id="propriedade_prodepa" name="propriedade_prodepa" class="form-control" onchange="habilitarFornecedor();">
                                        <option value="1" selected>Sim</option>
                                        <option value="0">Não</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="lid_fornecedor">Fornecedor </label>
                                    <?php echo $this->tag->textField(["lid_fornecedor", "size" => 120, "class" => "form-control", "disabled" => "true", "id" => "lid_fornecedor", "placeholder" => "Fornecedor", "onkeyup" => "autocompletarFornecedor();"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_fornecedor", "size" => 120, "class" => "form-control", "id" => "id_fornecedor"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="lid_contrato">Contrato </label>
                                    <?php echo $this->tag->textField(["lid_contrato", "size" => 120, "class" => "form-control", "id" => "lid_contrato", "placeholder" => "Contrato", "onkeyup" => "autocompletarContrato();"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_contrato", "size" => 120, "class" => "form-control", "id" => "id_contrato"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="descricao">Descrição <span class="required">*</span></label>
                                    <?= $this->tag->textField(["descricao", "size" => 200, "class" => "form-control", "id" => "descricao", "placeholder" => "Descrição do Terreno"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="comprimento">Comprimento </label>
                                    <?= $this->tag->textField(["comprimento", "size" => 200, "class" => "form-control valor_percentual", "id" => "comprimento", "placeholder" => "Comprimento do Terreno"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="largura">Largura </label>
                                    <?= $this->tag->textField(["largura", "size" => 200, "class" => "form-control valor_percentual", "id" => "largura", "placeholder" => "Largura do Terreno"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="area">Área </label>
                                    <?= $this->tag->textField(["area", "size" => 200, "class" => "form-control valor_percentual", "id" => "area", "placeholder" => "Área do Terreno"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="cep">CEP <span class="required">*</span></label>
                                    <?= $this->tag->textField(["cep", "size" => 200, "class" => "form-control cep", "id" => "cep", "onchange" => "preencherEndereco();", "placeholder" => "CEP do Terreno"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="endereco">Endereço <span class="required">*</span></label>
                                    <?= $this->tag->textField(["endereco", "size" => 200, "class" => "form-control", "id" => "endereco", "placeholder" => "Endereço do Terreno"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="numero">Número <span class="required">*</span></label>
                                    <?= $this->tag->textField(["numero", "size" => 200, "class" => "form-control", "id" => "numero", "placeholder" => "Número do Terreno"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="bairro">Bairro <span class="required">*</span></label>
                                    <?= $this->tag->textField(["bairro", "size" => 200, "class" => "form-control", "id" => "bairro", "placeholder" => "Bairro do Terreno"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="complemento">Complemento </label>
                                    <?= $this->tag->textField(["complemento", "size" => 200, "class" => "form-control", "id" => "complemento", "placeholder" => "Complemento do Terreno"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="cidade">Cidade <span class="required">*</span></label>
                                    <?= $this->tag->textField(["cidade", "size" => 200, "class" => "form-control", "id" => "cidade", "placeholder" => "Cidade do Terreno"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="estado">Estado <span class="required">*</span></label>
                                    <?= $this->tag->textField(["estado", "size" => 200, "class" => "form-control", "id" => "estado", "placeholder" => "Estado do Terreno"]) ?>
                                    <input type="hidden" id="sigla_estado" name="sigla_estado" value=""><!-- Manter como hidden -->
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="latitude">Latitude </label>
                                    <?= $this->tag->textField(["latitude", "size" => 200, "class" => "form-control", "id" => "latitude", "placeholder" => "Latitude do Terreno"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="longitude">Longitude </label>
                                    <?= $this->tag->textField(["longitude", "size" => 200, "class" => "form-control", "id" => "longitude", "placeholder" => "Longitude do Terreno"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="confirmaCancelar('modalCadastro');">Fechar</button>
                        <button id="salvarCadastro" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light" onclick="salvar();" value="">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->