<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Auth\Autentica;
use Util\Infra;
use Util\Util;

$util = new Util();
$infra = new Infra();
$auth = new Autentica();
$security_plugin = new SecurityPlugin();
$acl = $security_plugin->getAcl();
$role = $auth->getRoles();
$module = $this->router->getControllerName();

?>

<?= $this->getContent(); ?>

<div class="col-12">
    <?= $this->tag->form(
        [
            "contrato_fiscal",
            "autocomplete" => "off",
            "id" => "formPesquisa"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?= $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="bt_menu_tabela">
                <?= $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
                <button type="button" name="bt_limpar" id="bt_limpar" class="btn btn-warning btn-rounded waves-light w-md" onclick="limpar();">Limpar</button>
                <?php if($acl->isAllowed($role,$module, 'criar')): ?>
                    <button type="button" name="bt_novo" id="bt_novo" class="btn btn-success btn-rounded waves-light w-md" onclick="criar();">Novo</button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?= $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="datatable_listar" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Tipo</th>
                <th>Nome</th>
                <th>Data Nomeação</th>
                <th>Ativo</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page as $contratofiscal): ?>
                <?php
                switch($contratofiscal->getAtivo())
                {
                    case '0'://Inativo (False)
                        $ativo = "Inativo";
                        $class_tr = 'class="table-danger"';
                        break;
                    case '1'://Ativo (True)
                        $ativo = "Ativo";
                        $class_tr = null;
                        break;
                }
                switch($contratofiscal->getTipoFiscal())
                {
                    case '0'://Suplente (False)
                        $tipo_fiscal = "Suplente";
                        break;
                    case '1'://Titular (True)
                        $tipo_fiscal = "Titular";
                        break;
                }
                ?>
                <tr <?= $class_tr; ?>>
                    <td><?= $contratofiscal->getId() ?></td>
                    <td><?= $tipo_fiscal ?></td>
                    <td><?= $contratofiscal->getNomeFiscal() ?></td>
                    <td><?= $util->converterDataHoraParaBr($contratofiscal->getDataNomeacao()) ?></td>
                    <td><?= $ativo ?></td>
                    <td class="td_acoes">
                        <?php if($acl->isAllowed($role,$module, 'visualizar')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $contratofiscal->getId() ?>, true);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.png" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                        <?php endif; ?>
                        <?php if($contratofiscal->getAtivo() == '0'): ?>
                            <?php if($acl->isAllowed($role, $module, 'ativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="ativar(<?= $contratofiscal->getId() ?>, '<?= $contratofiscal->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.png" title="Ativar" alt="Ativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($acl->isAllowed($role, $module, 'subir')): ?> <!-- Anexo de Arquivos -->
                                <a href="javascript:void(0)" class="botoes_acao" onclick="criarAnexo(<?= $contratofiscal->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/upload.png" title="Anexar Arquivo" alt="Anexar Arquivo" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'editar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $contratofiscal->getId() ?>, false);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.png" title="Editar" alt="Editar" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'inativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="inativar(<?= $contratofiscal->getId() ?>, '<?= $contratofiscal->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.png" title="Desativar" alt="Desativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($acl->isAllowed($role, $module, 'excluir')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="excluir(<?= $contratofiscal->getId() ?>, '<?= $contratofiscal->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.png" title="Excluir" alt="Excluir" height="25" width="25"></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Cadastro -->
<div id="modalCadastro" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalCadastro" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="confirmaCancelar('modalCadastro');">×</button>
                <h5 class="modal-title" id="modalCadastro">Dados do Fiscal do Contrato</h5>
            </div>
            <form id="formCadastro">
                <input type="hidden" id="token" name="<?= $token['tokenKey'] ?>" value="<?= $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-6 botoes_forms_alinhamento">
                                    <label for="lid_contrato_fiscal_pai">Departamento Principal </label>
                                    <?php echo $this->tag->textField(["lid_contrato_fiscal_pai", "size" => 120, "class" => "form-control", "id" => "lid_contrato_fiscal_pai", "placeholder" => "Departamento Principal", "onkeyup" => "autocompletarDepartamentoPrincipal('lid_contrato_fiscal_pai','id_contrato_fiscal_pai');"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_contrato_fiscal_pai", "size" => 120, "class" => "form-control", "id" => "id_contrato_fiscal_pai"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="descricao">Descrição <span class="required">*</span></label>
                                    <?= $this->tag->textField(["descricao", "size" => 200, "class" => "form-control", "id" => "descricao", "placeholder" => "Descrição da Torre"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="confirmaCancelar('modalCadastro');">Fechar</button>
                        <button id="salvarCadastro" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light" onclick="salvar();" value="">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal Upload de Anexos -->
<div id="modalAnexoArquivo" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalAnexoArquivo" aria-hidden="true"
     style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-65">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalAnexoArquivo">Anexar arquivos ao Fiscal.: <span id="identificador-anexado"></span></h5>
            </div>
            <form id="formAnexoArquivo" action="contrato/subir" enctype="multipart/form-data" method="POST">
                <input type="hidden" id="id_contrato_fiscal" name="id_contrato_fiscal" value=""><!-- Manter como hidden -->
                <div class="modal-body">
                    <table id="tabela_lista_anexos" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="display: none;">
                        <thead>
                        <tr>
                            <th colspan="4" class="fonte-15">Lista de Anexos</th>
                        </tr>
                        <tr>
                            <th width="25%">Tipo Anexo</th>
                            <th width="35%">Descrição</th>
                            <th width="25%">Data de Inclusão</th>
                            <th width="15%">Ações</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    <div class="form-row">
                        <button type="button" name="bt_inserir_anexo" id="bt_inserir_anexo" class="btn btn-info btn-rounded waves-light w-md" onclick="inserirAnexo();">Novo Anexo</button>
                    </div>
                    <div id="agrupamento-anexos">
                        <div class="form-row" style="margin-top: 20px;">
                            <div class="form-group col-md-3">
                                <label for="id_tipo_anexo">Tipo de Anexo <span class="required">*</span></label>
                                <?= $this->tag->select(["id_tipo_anexo[]", $tipos_anexos, "class" => "form-control selectpicker", "id" => "id_tipo_anexo", "data-live-search" => "true", "data-style" => "btn-light",
                                    "using" => ["id", "descricao",],
                                    "useEmpty" => true,
                                    "emptyText" => "Selecione o Tipo de Anexo",
                                    "emptyValue" => ""])
                                ?>
                            </div>
                            <div class="form-group col-md-3 botoes_forms_alinhamento">
                                <label for="descricao">Descrição </label>
                                <?= $this->tag->textField(["descricao[]", "size" => 200, "class" => "form-control", "id" => "descricao", "placeholder" => "Descrição"]) ?>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="anexo">Anexo <span class="required">*</span></label>
                                <?= $this->tag->fileField(["anexo", "class" => "filestyle", "id" => "anexo"]) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModalAnexos();" data-dismiss="modal">Fechar</button>
                        <button id="salvarAnexoArquivo" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->