<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title float-left">Dashboard</h4>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item">
                    <?php echo $this->tag->linkTo(["index", "Dashboard"]) ?>
                </li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<!--Sessão de Gráficos-->
<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="header-title">Bar Chart</h4>

            <canvas id="bar" height="350" class="mt-4"></canvas>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="header-title">Line Chart</h4>

            <canvas id="lineChart" height="350" class="mt-4"></canvas>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="header-title">Pie Chart</h4>

            <canvas id="pie" height="350" class="mt-4"></canvas>

        </div>
    </div>

    <div class="col-lg-6">

        <div class="card-box">
            <h4 class="header-title">Donut Chart</h4>

            <canvas id="doughnut" height="350" class="mt-4"></canvas>

        </div>
    </div>

</div>
<!-- end row -->


<div class="row">

    <div class="col-lg-6">

        <div class="card-box">
            <h4 class="header-title">Polar area Chart</h4>

            <canvas id="polarArea" height="350" class="mt-4"> </canvas>

        </div>
    </div>

    <div class="col-lg-6">
        <div class="card-box">
            <h4 class="header-title">Radar Chart</h4>

            <canvas id="radar" height="350" class="mt-4"></canvas>

        </div>
    </div>

</div>
<!-- end row -->
