<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title float-left">Dashboard</h4>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item">
                    <?php echo $this->tag->linkTo(["index", "Dashboard"]) ?>
                </li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>

<!--Sessão de Gráficos-->
<div class="row">
    <div class="col-lg-6">
        <div id="pie_circuitos_status" height="350" class="mt-4"></div>
    </div>
    <div class="col-lg-6">
        <div id="pie_cidade_digital_status" height="350" class="mt-4"></div>
    </div>
</div>
<!-- end row -->
<div class="row">
    <div class="col-lg-6">
        <div id="pie_circuitos_link" height="350" class="mt-4"></div>
    </div>
    <div class="col-lg-6">
        <div id="pie_clientes_esfera" height="350" class="mt-4"></div>
    </div>
</div>
<!-- end row -->
<div class="row">
    <div class="col-lg-6">
        <div id="pie_ativacao_link_mes" height="350" class="mt-4"></div>
    </div>
    <div class="col-lg-6">
        <div id="pie_ativacoes_desativacoes_mes" height="350" class="mt-4"></div>
    </div>
</div>
<!-- end row -->
<div class="row">
    <div class="col-lg-6">
        <div id="pie_circuitos_funcao" height="350" class="mt-4"></div>
    </div>
    <div class="col-lg-6">
        <div id="pie_circuitos_acesso" height="350" class="mt-4"></div>
    </div>
</div>
<!-- end row -->
<div class="row">
    <div class="col-lg-6">
        <div id="pie_circuitos_conectividade" height="350" class="mt-4"></div>
    </div>
    <!--    <div class="col-lg-6">-->
    <!--        <div class="card-box">-->
    <!--            <h4 class="header-title">Circuitos por Cidade Digital</h4>-->
    <!--            <div id="bar_circuitos_cidade_digital" height="350" class="mt-4"></div>-->
    <!--        </div>-->
    <!--    </div>-->
</div>
<!-- end row -->
<!--<div class="row">-->
<!--    <div class="col-lg-12">-->
<!--        <div class="card-box">-->
<!--            <h4 class="header-title">Hotzones por Cidade</h4>-->
<!--            <div id="bar_hotzones_cidade" height="350" class="mt-4"></div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!-- end row -->
<!--<div class="row">-->
<!--    <div class="col-lg-12">-->
<!--        <div class="card-box">-->
<!--            <h4 class="header-title">Cluster por Cidade</h4>-->
<!--            <div id="bar_cluster_cidade" height="350" class="mt-4"></div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!-- end row -->
<!--<div class="row">-->
<!--    <div class="col-lg-6">-->
<!--        <div class="card-box">-->
<!--            <h4 class="header-title">Equipamentos por Fabricante</h4>-->
<!--            <div id="bar_equipamentos_fabricante" height="350" class="mt-4"></div>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="col-lg-6">-->
<!--        <div class="card-box">-->
<!--            <h4 class="header-title">Equipamentos por Tipo</h4>-->
<!--            <div id="bar_equipamentos_tipo" height="350" class="mt-4"></div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!-- end row -->
<!--<div class="row">-->
<!--    <div class="col-lg-6">-->
<!--        <div class="card-box">-->
<!--            <h4 class="header-title">Top 20 Clientes com as maiores quantidades de Circuitos</h4>-->
<!--            <div id="bar_top20_clientes" height="350" class="mt-4"></div>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="col-lg-6">-->
<!--        <div class="card-box">-->
<!--            <h4 class="header-title">Circuitos por Banda</h4>-->
<!--            <div id="bar_circuitos_conectividade" height="350" class="mt-4"></div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
<!-- end row -->
<!--Fim da Sessão de Gráficos-->