<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search cliente_unidade
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["cliente_unidade/new", "Create cliente_unidade"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "cliente_unidade/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdPessoa" class="col-sm-2 control-label">Id Of Pessoa</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_pessoa", "type" => "number", "class" => "form-control", "id" => "fieldIdPessoa"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdCliente" class="col-sm-2 control-label">Id Of Cliente</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_cliente", "type" => "number", "class" => "form-control", "id" => "fieldIdCliente"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
