<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Auth\Autentica;
use Phalcon\Tag;
use Util\Infra;

$infra = new Infra();
$auth = new Autentica();
$security_plugin = new SecurityPlugin();
$acl = $security_plugin->getAcl();
$role = $auth->getRoles();
$module = $this->router->getControllerName();

?>

<?= $this->getContent(); ?>

<div class="col-12">
    <?= $this->tag->form(
        [
            "set_equipamento/index",
            "autocomplete" => "off",
            "id" => "formPesquisa"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?= $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="bt_menu_tabela">
                <?= $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
                <button type="button" name="bt_limpar" id="bt_limpar" class="btn btn-warning btn-rounded waves-light w-md" onclick="limpar();">Limpar</button>
                <?php if($acl->isAllowed($role,$module, 'criar')): ?>
                    <button type="button" name="bt_novo" id="bt_novo" class="btn btn-success btn-rounded waves-light w-md" onclick="criar();">Novo</button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?= $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="datatable_listar" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Set de Equipamentos</th>
                <th>Ativo</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page as $setequipamento): ?>
                <?php
                switch($setequipamento->getAtivo())
                {
                    case '0'://Inativo (False)
                        $ativo = "Inativo";
                        $class_tr = 'class="table-danger"';
                        break;
                    case '1'://Ativo (True)
                        $ativo = "Ativo";
                        $class_tr = null;
                        break;
                }
                ?>
                <tr <?= $class_tr; ?>>
                    <td><?= $setequipamento->getId() ?></td>
                    <td><?= $setequipamento->getDescricao() ?></td>
                    <td><?= $ativo ?></td>
                    <td class="td_acoes">
                        <?php if($acl->isAllowed($role,$module, 'visualizar')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $setequipamento->getId() ?>, true);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.png" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                        <?php endif; ?>
                        <?php if($setequipamento->getAtivo() == '0'): ?>
                            <?php if($acl->isAllowed($role, $module, 'ativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="ativar(<?= $setequipamento->getId() ?>, '<?= $setequipamento->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.png" title="Ativar" alt="Ativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($acl->isAllowed($role, $module, 'editar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $setequipamento->getId() ?>, false);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.png" title="Editar" alt="Editar" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'inativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="inativar(<?= $setequipamento->getId() ?>, '<?= $setequipamento->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.png" title="Desativar" alt="Desativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($acl->isAllowed($role, $module, 'excluir')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="excluir(<?= $setequipamento->getId() ?>, '<?= $setequipamento->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.png" title="Excluir" alt="Excluir" height="25" width="25"></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Cadastro -->
<div id="modalCadastro" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalCadastro" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="confirmaCancelar('modalCadastro');">×</button>
                <h5 class="modal-title" id="modalCadastro">Dados do Set de Equipamentos</h5>
            </div>
            <form id="formCadastro">
                <input type="hidden" id="token" name="<?= $token['tokenKey'] ?>" value="<?= $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a href="#tab_set_equipamento" data-toggle="tab" aria-expanded="true" class="nav-link active">
                                Set de Equipamentos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#tab_compenente" data-toggle="tab" aria-expanded="false" class="nav-link">
                                Componentes
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab_set_equipamento">
                            <div class="form-row">
                                <div class="col-12">
                                    <div class="form-row">
                                        <div class="form-group col-md-12">
                                            <label for="descricao">Descrição <span class="required">*</span></label>
                                            <?= $this->tag->textField(["descricao", "size" => 200, "class" => "form-control result", "id" => "descricao", "placeholder" => "Descrição do Set de Equipamentos"]) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="tab_compenente">
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <button type="button" name="bt_novo_componente" id="bt_novo_componente" class="btn btn-success btn-rounded waves-light w-md hide_buttons" onclick="criarComponente();">Novo</button>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12" id="div_tabela_componentes">
                                    <table id="tabela_componentes" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%"  style="display: none;">
                                        <thead>
                                        <tr style="text-align: center;">
                                            <td>Fornecedor</td>
                                            <td>Número de Série / Patrimônio</td>
                                            <td>Fabricante</td>
                                            <td>Modelo</td>
                                            <td>Equipamento</td>
                                            <td>Ações</td>
                                        </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>
                                </div>
                            </div>
                            <div id="dados_componente" style="display: none;">
                                <div class="form-row">
                                    <div class="form-group col-md-3">
                                        <label for="lnumero_serie">Número de Série / Patrimônio</label>
                                        <?php echo $this->tag->textField(["i_lnumero_serie", "size" => 60, "class" => "form-control", "id" => "i_lnumero_serie", "onchange" => "changeEquipamento();", "placeholder" => "Número de Série / Patrimônio"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_numero_serie", "size" => 60, "class" => "form-control", "id" => "i_numero_serie"]) ?>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="lid_fabricante">Fabricante </label>
                                        <?php echo $this->tag->textField(["i_lid_fabricante", "size" => 150, "class" => "form-control", "id" => "i_lid_fabricante", "placeholder" => "Fabricante", "onkeyup" => "autocompletarFabricante();"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_fabricante", "size" => 150, "class" => "form-control", "id" => "i_id_fabricante"]) ?>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="lid_modelo">Modelo </label>
                                        <?php echo $this->tag->textField(["i_lid_modelo", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "i_lid_modelo", "placeholder" => "Modelo", "onkeyup" => "autocompletarModelo();"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_modelo", "size" => 60, "class" => "form-control", "id" => "i_id_modelo"]) ?>
                                    </div>
                                    <div class="form-group col-md-3">
                                        <label for="lid_equipamento">Equipamento <span class="required">*</span></label>
                                        <?php echo $this->tag->textField(["i_lid_equipamento", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "i_lid_equipamento", "placeholder" => "Equipamento", "onkeyup" => "autocompletarEquipamento();"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_equipamento", "size" => 60, "class" => "form-control", "id" => "i_id_equipamento"]) ?>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="i_lid_fornecedor">Fornecedor <span class="required">*</span></label>
                                        <?php echo $this->tag->textField(["i_lid_fornecedor", "size" => 120, "class" => "form-control", "id" => "i_lid_fornecedor", "placeholder" => "Fornecedor", "onkeyup" => "autocompletarFornecedor('i_lid_fornecedor','i_id_fornecedor');"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_fornecedor", "size" => 120, "class" => "form-control", "id" => "i_id_fornecedor"]) ?>
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="i_lid_contrato">Contrato </label>
                                        <?php echo $this->tag->textField(["i_lid_contrato", "size" => 120, "class" => "form-control", "id" => "i_lid_contrato", "placeholder" => "Contrato", "onkeyup" => "autocompletarContrato('i_lid_contrato','i_id_contrato');"]) ?>
                                        <?php echo $this->tag->hiddenField(["i_id_contrato", "size" => 120, "class" => "form-control", "id" => "i_id_contrato"]) ?>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <button type="button" name="bt_inserir_componente" id="bt_inserir_componente" class="btn btn-info btn-rounded waves-light w-md bt_menu_tabela hide_buttons" onclick="inserirComponente();">Inserir</button>
                                        <button type="button" name="bt_cancelar_componente" id="bt_cancelar_componente" class="btn btn-danger btn-rounded waves-light w-md bt_menu_tabela" onclick="cancelarComponente();">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparDadosFormComponente();confirmaCancelar('modalCadastro');">Fechar</button>
                        <button id="salvarCadastro" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light" onclick="salvar();" value="">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->