<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Phalcon\Tag;

?>

<?php echo $this->getContent(); ?>

<div class="col-12">

</div>

<div class="col-12">
    <div class="card-box">
        <table id="tb_logs" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Item</th>
                <th>Logs</th>
            </tr>
            </thead>
            <tbody>
            <?php $i = 1; ?>
            <?php foreach ($page as $log) {?>
                <tr>
                    <td><?php echo $i; ?></td>
                    <td><?php echo $log; ?></td>
                </tr>
                <?php $i++; ?>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>