<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Auth\Autentica;
use Phalcon\Tag;
use Util\Infra;

$infra = new Infra();
$auth = new Autentica();
$security_plugin = new SecurityPlugin();
$acl = $security_plugin->getAcl();
$role = $auth->getRoles();
$module = $this->router->getControllerName();

?>

<?= $this->getContent(); ?>

<div class="col-12">
    <?= $this->tag->form(
        [
            "conectividade/index",
            "autocomplete" => "off"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?= $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="bt_menu_tabela">
                <?= $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
                <button type="button" name="bt_limpar" id="bt_limpar" class="btn btn-warning btn-rounded waves-light w-md">Limpar</button>
                <?php if($acl->isAllowed($role,$module, 'index')): ?>
                    <button type="button" name="bt_novo" id="bt_novo" class="btn btn-success btn-rounded waves-light w-md">Novo</button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?= $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="tb_conectividade" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Tipo</th>
                <th>Conectividade</th>
                <th>Endereço</th>
                <th>Ativo</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $conectividade): ?>
                <?php
                switch($conectividade->getAtivo())
                {
                    case '0'://Inativo (False)
                        $ativo = "Inativo";
                        $class_tr = 'class="table-danger"';
                        $display = 'style="display: none;"';
                        break;
                    case '1'://Ativo (True)
                        $ativo = "Ativo";
                        $class_tr = null;
                        break;
                }
                ?>
                <tr <?= $class_tr; ?>>
                    <td><?= $conectividade->getId() ?></td>
                    <td><?= $conectividade->getTipoConectividade() ?></td>
                    <td><?= $conectividade->getDescricao() ?></td>
                    <td><?= $conectividade->getEndereco() ?></td>
                    <td><?= $ativo ?></td>
                    <td class="td_acoes">
                        <?php if($acl->isAllowed($role,$module, 'index')): ?>
                            <a href="javascript:void(0)" class="botoes_acao"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.png" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                        <?php endif; ?>
                        <?php if($conectividade->getAtivo() == '0'): ?>
                            <?php if($acl->isAllowed($role, $module, 'index')): ?>
                                <a href="javascript:void(0)" class="botoes_acao"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.png" title="Ativar" alt="Ativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($acl->isAllowed($role, $module, 'index')): ?>
                                <a href="javascript:void(0)" class="botoes_acao"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.png" title="Editar" alt="Editar" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'index')): ?>
                                <a href="javascript:void(0)" class="botoes_acao"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.png" title="Desativar" alt="Desativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($acl->isAllowed($role, $module, 'index')): ?>
                            <a href="javascript:void(0)" class="botoes_acao"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.png" title="Excluir" alt="Excluir" height="25" width="25"></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Conectividade -->
<div id="modalconectividade" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalconectividade" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalconectividade">Dados da Conectividade</h5>
            </div>
            <form id="formConectividade">
                <input type="hidden" id="token" name="<?= $token['tokenKey'] ?>" value="<?= $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="id_tipo">Tipo Conectividade <span class="required">*</span></label>
                                    <?= $this->tag->select(["id_tipo_t", $tipocd, "class" => "form-control concat", "id" => "id_tipo_t",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um tipo",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="descricao">Conectividade <span class="required">*</span></label>
                                    <?= $this->tag->textField(["descricao_t", "size" => 200, "class" => "form-control result", "id" => "descricao_t", "placeholder" => "Descrição da Conectividade"]) ?>
                                </div>
                                <div class="form-group col-md-10">
                                    <label for="endereco">Endereço da Conectividade</label>
                                    <?= $this->tag->textField(["endereco_t", "size" => 200, "class" => "form-control", "id" => "endereco_t", "placeholder" => "Endereço da Conectividade"]) ?>
                                </div>
                                <div class="form-group col-md-1">
                                    <button id="add_conectividade" name="add_conectividade" type="button" class="btn btn-sucess btn-rounded waves-light waves-effect bt_inserir">Inserir</button>
                                </div>
                            </div>
                            <div class="form-row">
                                <table id="tb_conectividade" class="table table-hover" style="display: none;">
                                    <thead>
                                    <tr>
                                        <th>Tipo</th>
                                        <th>Conectividade</th>
                                        <th>Endereço</th>
                                        <th>Excluir?</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" data-dismiss="modal">Fechar</button>
                        <button id="salvarConectividade" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->