<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Phalcon\Tag;
use Util\Infra;

$infra = new Infra();

?>

<?php echo $this->getContent(); ?>

<div class="col-12">
    <?php
    echo $this->tag->form(
        [
            "conectividade/index",
            "autocomplete" => "off"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="bt_menu_tabela">
                <?php echo $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
                <button name="bt_novo" id="bt_novo" class="btn btn-info btn-rounded waves-light w-md">Limpar</button>
                <button name="bt_novo" id="bt_novo" class="btn btn-success btn-rounded waves-light w-md">Novo</button>
            </div>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="tb_conectividade" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Conectividade</th>
                <th>Ativo</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>1</td>
                <td>Conectividade Teste</td>
                <td>Ativo</td>
                <td align="center">
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.gif" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.gif" title="Editar" alt="Editar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.gif" title="Ativar" alt="Ativar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.gif" title="Desativar" alt="Desativar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/movimentar.gif" title="Movimentar" alt="Movimentar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.gif" title="Excluir" alt="Excluir" height="25" width="25"></a>
                </td>
            </tr>
            <tr>
                <td>2</td>
                <td>Conectividade Teste</td>
                <td>Ativo</td>
                <td align="center">
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.gif" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.gif" title="Editar" alt="Editar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.gif" title="Ativar" alt="Ativar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.gif" title="Desativar" alt="Desativar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/movimentar.gif" title="Movimentar" alt="Movimentar" height="25" width="25"></a>
                    <a href="javascript:void(0)"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.gif" title="Excluir" alt="Excluir" height="25" width="25"></a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal CidadeDigital -->
<!--<div id="modalconectividade" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalconectividade" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">-->
<!--    <div class="modal-dialog modal-lg">-->
<!--        <div class="modal-content">-->
<!--            <div class="modal-header">-->
<!--                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
<!--                <h5 class="modal-title" id="modalconectividade">Dados da Conectividade</h5>-->
<!--            </div>-->
<!--            <form id="formCidadeDigital">-->
<!--                <input type="hidden" id="token" name="--><?php //echo $token['tokenKey'] ?><!--" value="--><?php //echo $token['tokenValue'] ?><!--"> <!-- CSRFToken Control -->-->
<!--                <div class="modal-body">-->
<!--                    <div class="form-row">-->
<!--                        <div class="col-12">-->
<!--<!--                            <h6>Dados da Conectividade</h6>-->-->
<!--                            <div class="form-row">-->
<!--                                <div class="form-group col-md-6">-->
<!--                                    <label for="id_cidade">Cidade <span class="required">*</span></label>-->
<!--                                    --><?php //echo $this->tag->select(["id_cidade", $cidades, "class" => "form-control concat", "id" => "id_cidade",
//                                        "using" => ["id", "cidade",],
//                                        "useEmpty" => true,
//                                        "emptyText" => "Selecione uma Cidade",
//                                        "emptyValue" => ""])
//                                    ?>
<!--                                </div>-->
<!--                                <div class="form-group col-md-6">-->
<!--                                    <label for="descricao">Conectividade <span class="required">*</span></label>-->
<!--                                    --><?php //echo $this->tag->textField(["descricao", "size" => 200, "class" => "form-control result", "id" => "descricao", "placeholder" => "Descrição da Conectividade"]) ?>
<!--                                </div>-->
<!--                            </div>-->
<!--                            <h6>Conectividades da Conectividade</h6>-->
<!--                            <div class="form-row">-->
<!--                                <div class="form-group col-md-6">-->
<!--                                    <label for="id_tipo">Tipo Conectividade <span class="required">*</span></label>-->
<!--                                    --><?php //echo $this->tag->select(["id_tipo_t", $tipocd, "class" => "form-control concat", "id" => "id_tipo_t",
//                                        "using" => ["id", "descricao",],
//                                        "useEmpty" => true,
//                                        "emptyText" => "Selecione um tipo",
//                                        "emptyValue" => ""])
//                                    ?>
<!--                                </div>-->
<!--                                <div class="form-group col-md-6">-->
<!--                                    <label for="descricao">Conectividade <span class="required">*</span></label>-->
<!--                                    --><?php //echo $this->tag->textField(["descricao_t", "size" => 200, "class" => "form-control result", "id" => "descricao_t", "placeholder" => "Descrição da Conectividade"]) ?>
<!--                                </div>-->
<!--                                <div class="form-group col-md-10">-->
<!--                                    <label for="endereco">Endereço da Conectividade</label>-->
<!--                                    --><?php //echo $this->tag->textField(["endereco_t", "size" => 200, "class" => "form-control", "id" => "endereco_t", "placeholder" => "Endereço da Conectividade"]) ?>
<!--                                </div>-->
<!--                                <div class="form-group col-md-1">-->
<!--                                    <button id="add_conectividade" name="add_conectividade" type="button" class="btn btn-sucess btn-rounded waves-light waves-effect bt_inserir">Inserir</button>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                            <div class="form-row">-->
<!--                                <table id="tb_conectividade" class="table table-hover" style="display: none;">-->
<!--                                    <thead>-->
<!--                                        <tr>-->
<!--                                            <th>Tipo</th>-->
<!--                                            <th>Conectividade</th>-->
<!--                                            <th>Endereço</th>-->
<!--                                            <th>Excluir?</th>-->
<!--                                        </tr>-->
<!--                                    </thead>-->
<!--                                    <tbody>-->
<!--                                    </tbody>-->
<!--                                </table>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="modal-footer">-->
<!--                    <div class="form-group col-md-6">-->
<!--                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>-->
<!--                    </div>-->
<!--                    <div class="form-group col-md-6 botoes_rodape">-->
<!--                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->-->
<!--                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" data-dismiss="modal">Fechar</button>-->
<!--                        <button id="salvarCidadeDigital" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>-->
<!--                    </div>-->
<!--                </div><!-- /.modal-footer -->-->
<!--            </form>-->
<!--        </div><!-- /.modal-content -->-->
<!--    </div><!-- /.modal-dialog -->-->
<!--</div><!-- /.modal -->-->