<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Phalcon\Tag;

?>

<?php echo $this->getContent(); ?>

<div class="col-12">
    <?php
    echo $this->tag->form(
        [
            "equipamento/index",
            "autocomplete" => "off"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <div class="bt_menu_tabela">
                <?php echo $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
            </div>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="tb_equipamento" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Fabricante</th>
                    <th>Modelo</th>
                    <th>Tipo</th>
                    <th>Equipamento</th>
                    <th>Nº Série</th>
                    <th>Nº Patrimônio</th>
                    <th>Ativo</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $equipamento): ?>
            <?php
                switch($equipamento->ativo){
                    case '0'://Inativo (False)
                    $ativo = "Inativo";
                    break;
                    case '1'://Ativo (True)
                    $ativo = "Ativo";
                    break;
                }
            ?>
                    <tr>
                        <td><?php echo $equipamento->id ?></td>
                        <td><?php echo $equipamento->Fabricante->Pessoa->nome ?></td>
                        <td><?php echo $equipamento->Modelo->modelo ?></td>
                        <td><?php echo $equipamento->Lov->descricao ?></td>
                        <td><?php echo $equipamento->nome ?></td>
                        <td><?php echo $equipamento->numserie ?></td>
                        <td><?php echo $equipamento->numpatrimonio ?></td>
                        <td><?php echo $ativo ?></td>
                    </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Equipamento -->
<div id="modalequipamento" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalequipamento" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalequipamento">Dados de Equipamentos</h5>
            </div>
            <form id="formEquipamento">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="id_fabricante">Fabricante <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_fabricante", $fabricante, "class" => "form-control", "id" => "id_fabricante",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o fabricante",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="id_modelo">Modelo <span class="required">*</span></label>
                                    <select disabled name="id_modelo" id="id_modelo" class="form-control">
                                        <option value="">Selecione o modelo</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="id_tipoequipamento">Tipo de Equipamento <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_tipoequipamento", $tipoequipamento, "class" => "form-control", "id" => "id_tipoequipamento",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="nome">Nome do Equipamento</label>
                                    <?php echo $this->tag->textField(["nome", "size" => 200, "class" => "form-control", "id" => "nome", "placeholder" => "Nome do Equipamento"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="numserie">Número de Série <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["numserie", "size" => 60, "class" => "form-control", "id" => "numserie", "placeholder" => "Número de Série"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="numpatrimonio">Número de Patrimônio <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["numpatrimonio", "size" => 60, "class" => "form-control", "id" => "numpatrimonio", "placeholder" => "Número de Patrimônio"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="descricao">Descrição do Equipamento</label>
                                    <?php echo $this->tag->textArea(["descricao", "size" => 200, "class" => "form-control", "id" => "descricao", "placeholder" => "Descricao"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" data-dismiss="modal">Fechar</button>
                        <button id="salvarEquipamento" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->