<div class="col-12">
    <div class="card-box">
        <table id="tb_modelo" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Fabricante</th>
                    <th>Modelo</th>
                    <th>Ativo</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $modelo): ?>
            <?php
                switch($modelo->ativo){
                    case '0'://Inativo (False)
                    $ativo = "Inativo";
                    break;
                    case '1'://Ativo (True)
                    $ativo = "Ativo";
                    break;
                }
            ?>
                    <tr>
                        <td><?php echo $modelo->id ?></td>
                        <td><?php echo $modelo->Fabricante->Pessoa->nome ?></td>
                        <td><?php echo $modelo->modelo ?></td>
                        <td><?php echo $ativo ?></td>
                    </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Modelo -->
<div id="modalmodelo" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalmodelo" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalmodelo">Dados de Modelos</h5>
            </div>
            <form id="formModelo">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-5">
                                    <?php echo $this->tag->select(["id_fabricante", $fabricante, "class" => "form-control", "id" => "id_fabricante",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um fabricante",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-7">
                                    <?php echo $this->tag->textField(["modelo", "size" => 200, "class" => "form-control", "id" => "modelo", "placeholder" => "Nome do Modelo"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <?php echo $this->tag->textArea(["descricao", "size" => 200, "class" => "form-control", "id" => "descricao", "placeholder" => "Descricao"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                    <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" data-dismiss="modal">Fechar</button>
                    <button id="salvarModelo" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->