<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search modelo
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["modelo/new", "Create modelo"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "modelo/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdFabricante" class="col-sm-2 control-label">Id Of Fabricante</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_fabricante", "type" => "number", "class" => "form-control", "id" => "fieldIdFabricante"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldModelo" class="col-sm-2 control-label">Modelo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["modelo", "size" => 30, "class" => "form-control", "id" => "fieldModelo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescricao" class="col-sm-2 control-label">Descricao</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["descricao", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescricao"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAtivo" class="col-sm-2 control-label">Ativo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["ativo", "type" => "number", "class" => "form-control", "id" => "fieldAtivo"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
