<?php

use Util\Util;

?>

<div class="col-12">
    <div class="card-box">
        <table id="tb_circuitos" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Designação</th>
                    <th>Cliente</th>
                    <th>Unidade</th>
                    <th>Função</th>
                    <th>Enlace</th>
                    <th>Data Cadastro</th>
                    <th>Data Atualização</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($page->items as $circuitos): ?>
                <?php            
                $util = new Util();
                $data_cadastro = ($circuitos->data_ativacao) ? $util->converterDataHoraParaBr($circuitos->data_ativacao) : null;
                $data_atualizacao = ($circuitos->data_atualizacao) ? $util->converterDataHoraParaBr($circuitos->data_atualizacao) : null;
                switch($circuitos->Cliente->id_tipocliente)
                {
                    case "45"://Pessoa Física
                        $unidade = null;
                    break;
                    case "44"://Pessoa Jurídica
                        $unidade = $circuitos->ClienteUnidade->Pessoa->nome;
                    break;
                }
            ?>
                <tr>
                    <td>
                        <?php echo $circuitos->id ?>
                    </td>
                    <td>
                        <?php echo $circuitos->designacao ?>
                    </td>
                    <td>
                        <?php echo $circuitos->Cliente->Pessoa->nome ?>
                    </td>
                    <td>
                        <?php echo $unidade ?>
                    </td>
                    <td>
                        <?php echo $circuitos->Lov5->descricao ?>
                    </td>
                    <td>
                        <?php echo $circuitos->Lov6->descricao ?>
                    </td>
                    <td>
                        <?php echo $data_cadastro ?>
                    </td>
                    <td>
                        <?php echo $data_atualizacao ?>
                    </td>
                    <td>
                        <?php echo $circuitos->Lov2->descricao ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Circuitos -->
<div id="modalcircuitos" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalcircuitos" aria-hidden="true"
    style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalcircuitos">Dados do Circuito</h5>
            </div>
            <form id="formCircuitos">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>">
                <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <input type="hidden" id="tipocliente" name="tipocliente" value=""><!-- Manter como hidden -->
                                    <?php echo $this->tag->select(["id_cliente", $clientes, "class" => "form-control", "id" => "id_cliente",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Cliente",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <select disabled name="id_cliente_unidade" id="id_cliente_unidade" class="form-control">
                                        <option value="">Selecione uma Unidade</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->textField(["designacao", "size" => 60, "class" => "form-control", "id" => "designacao", "placeholder" => "Designacao"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->textField(["vlan", "size" => 60, "class" => "form-control", "id" => "vlan", "placeholder" => "VLAN"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_contrato", $usacontrato, "class" => "form-control", "id" => "id_contrato",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Contrato",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_cluster", $cluster, "class" => "form-control", "id" => "id_cluster",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Cluster",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_tipounidade", $tipounindade, "class" => "form-control", "id" => "id_tipounidade",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Unidade",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_funcao", $funcao, "class" => "form-control", "id" => "id_funcao",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Função",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_enlace", $enlace, "class" => "form-control", "id" => "id_enlace",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o Enlace",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_fabricante", $fabricantes, "class" => "form-control", "id" => "id_fabricante",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Fabricante",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <select disabled name="id_modelo" id="id_modelo" class="form-control">
                                        <option value="">Selecione um Modelo</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <select disabled name="id_equipamento" id="id_equipamento" class="form-control">
                                        <option value="">Selecione um Equipamento</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->textField(["ip_redelocal", "size" => 30, "class" => "form-control ip", "id" => "ip_redelocal", "placeholder" => "IP Rede Local"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->textField(["ip_gerencia", "size" => 30, "class" => "form-control ip", "id" => "ip_gerencia", "placeholder" => "IP Rede Gerencial"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <?php echo $this->tag->textField(["ccode", "size" => 30, "class" => "form-control", "id" => "ccode", "placeholder" => "CCODE"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <?php echo $this->tag->textField(["tag", "size" => 120, "class" => "form-control", "id" => "tag", "placeholder" => "TAG"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <?php echo $this->tag->textField(["banda", "size" => 120, "class" => "form-control", "id" => "banda", "placeholder" => "Banda"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <?php echo $this->tag->textArea(["observacao", "size" => 400, "class" => "form-control", "id" => "observacao", "placeholder" => "Observação"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                    <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModal()" data-dismiss="modal">Fechar</button>
                    <button id="salvaCircuitos" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal Movimento -->
<div id="modalcircuitosmov" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalcircuitosmov" aria-hidden="true"
    style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalcircuitosmov">Dados do Movimmento</h5>
            </div>
            <form id="formCircuitosmov">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>">
                <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <input type="hidden" id="tipocliente" name="tipocliente" value=""><!-- Manter como hidden -->
                                    <?php echo $this->tag->select(["id_cliente", $clientes, "class" => "form-control", "id" => "id_cliente",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Cliente",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <select disabled name="id_cliente_unidade" id="id_cliente_unidade" class="form-control">
                                        <option value="">Selecione uma Unidade</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->textField(["designacao", "size" => 60, "class" => "form-control", "id" => "designacao", "placeholder" => "Designacao"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->textField(["vlan", "size" => 60, "class" => "form-control", "id" => "vlan", "placeholder" => "VLAN"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_contrato", $usacontrato, "class" => "form-control", "id" => "id_contrato",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Contrato",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_cluster", $cluster, "class" => "form-control", "id" => "id_cluster",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Cluster",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_tipounidade", $tipounindade, "class" => "form-control", "id" => "id_tipounidade",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Unidade",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_funcao", $funcao, "class" => "form-control", "id" => "id_funcao",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Função",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_enlace", $enlace, "class" => "form-control", "id" => "id_enlace",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o Enlace",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->select(["id_fabricante", $fabricantes, "class" => "form-control", "id" => "id_fabricante",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Fabricante",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <select disabled name="id_modelo" id="id_modelo" class="form-control">
                                        <option value="">Selecione um Modelo</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <select disabled name="id_equipamento" id="id_equipamento" class="form-control">
                                        <option value="">Selecione um Equipamento</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->textField(["ip_redelocal", "size" => 30, "class" => "form-control ip", "id" => "ip_redelocal", "placeholder" => "IP Rede Local"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <?php echo $this->tag->textField(["ip_gerencia", "size" => 30, "class" => "form-control ip", "id" => "ip_gerencia", "placeholder" => "IP Rede Gerencial"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <?php echo $this->tag->textField(["ccode", "size" => 30, "class" => "form-control", "id" => "ccode", "placeholder" => "CCODE"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <?php echo $this->tag->textField(["tag", "size" => 120, "class" => "form-control", "id" => "tag", "placeholder" => "TAG"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <?php echo $this->tag->textField(["banda", "size" => 120, "class" => "form-control", "id" => "banda", "placeholder" => "Banda"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <?php echo $this->tag->textArea(["observacao", "size" => 400, "class" => "form-control", "id" => "observacao", "placeholder" => "Observação"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="id" name="idmov" value=""><!-- Manter como hidden -->
                    <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModal()" data-dismiss="modal">Fechar</button>
                    <button id="salvaCircuitosmov" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->