<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Util\Util;

?>

<?php echo $this->getContent(); ?>

<div class="col-12">
    <?php
    echo $this->tag->form(
        [
            "circuitos/index",
            "autocomplete" => "off"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <div class="bt_menu_tabela">
                <?php echo $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
            </div>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="tb_circuitos" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th style="display: none;">Código</th>
                <th>Designação</th>
                <th>Cliente</th>
                <th>Unidade</th>
                <th>Cidade</th>
                <th>Tipo de Link</th>
                <th>IP de Gerência</th>
                <th>Função</th>
                <th>Tipo Acesso</th>
                <th>Banda</th>
                <!--                    <th>Data Cadastro</th>-->
                <!--                    <th>Data Atualização</th>-->
                <th>Status</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $circuitos): ?>
                <?php
                $util = new Util();
                switch($circuitos->Cliente->id_tipocliente)
                {
                    case "44"://Pessoa Física
                        $unidade = null;
                        break;
                    case "43"://Pessoa Jurídica
                        $unidade = $circuitos->ClienteUnidade->Pessoa->nome;
                        break;
                }
                $desc_tipolink = ($circuitos->id_tipolink) ? $circuitos->Lov6->descricao : "Campo Obrigatório";
                $desc_funcao = ($circuitos->id_funcao) ? $circuitos->Lov5->descricao : "Campo Obrigatório";
                $desc_tipoacesso = ($circuitos->id_tipoacesso) ? $circuitos->Lov4->descricao : "Campo Obrigatório";
                $desc_banda = ($circuitos->id_banda) ? $circuitos->Lov7->descricao : "Campo Obrigatório";
                $color_tipolink = (!$circuitos->id_tipolink) ? "style='font-weight: bold; color: red;'" : null;
                $color_funcao = (!$circuitos->id_funcao) ? "style='font-weight: bold; color: red;'" : null;
                $color_tipoacesso = (!$circuitos->id_tipoacesso) ? "style='font-weight: bold; color: red;'" : null;
                $color_banda = (!$circuitos->id_banda) ? "style='font-weight: bold; color: red;'" : null;
                $cidade = ($circuitos->CidadeDigital->EndCidade->cidade) ? $circuitos->CidadeDigital->EndCidade->cidade : null;
                ?>
                <tr>
                    <td style="display: none;">
                        <?php echo $circuitos->id ?>
                    </td>
                    <td>
                        <?php echo $circuitos->designacao ?>
                    </td>
                    <td>
                        <?php echo $circuitos->Cliente->Pessoa->nome ?>
                    </td>
                    <td>
                        <?php echo $unidade ?>
                    </td>
                    <td>
                        <?php echo $cidade ?>
                    </td>
                    <td <?php echo $color_tipolink ?>>
                        <?php echo $desc_tipolink ?>
                    </td>
                    <td>
                        <?php echo $circuitos->ip_gerencia ?>
                    </td>
                    <td <?php echo $color_funcao ?>>
                        <?php echo $desc_funcao ?>
                    </td>
                    <td <?php echo $color_tipoacesso ?>>
                        <?php echo $desc_tipoacesso ?>
                    </td>
                    <td <?php echo $color_banda ?>>
                        <?php echo $desc_banda ?>
                    </td>
                    <!--                    <td>-->
                    <!--                        --><?php //echo $data_cadastro ?>
                    <!--                    </td>-->
                    <!--                    <td>-->
                    <!--                        --><?php //echo $data_atualizacao ?>
                    <!--                    </td>-->
                    <td>
                        <?php echo $circuitos->Lov2->descricao ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<!--  Modal Circuitos -->
<div id="modalcircuitos" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalcircuitos" aria-hidden="true"
     style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalcircuitos">Dados do Circuito</h5>
            </div>
            <form id="formCircuitos">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>">
                <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <input type="hidden" id="tipocliente" name="tipocliente" value=""><!-- Manter como hidden -->
                                    <!--                                    <label for="id_cliente">Cliente <span class="required">*</span></label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_cliente", $clientes, "class" => "form-control", "id" => "id_cliente",
                                    //                                        "using" => ["id", "nome",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione um Cliente",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_cliente">Cliente <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_cliente", "size" => 150, "class" => "form-control", "id" => "lid_cliente", "placeholder" => "Cliente"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_cliente", "size" => 150, "class" => "form-control", "id" => "id_cliente"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <!--                                    <label for="id_cliente_unidade">Unidade do Cliente <span class="required">*</span></label>-->
                                    <!--                                    <select disabled name="id_cliente_unidade" id="id_cliente_unidade" class="form-control">-->
                                    <!--                                        <option value="">Selecione uma Unidade</option>-->
                                    <!--                                    </select>-->
                                    <label for="lid_cliente_unidade">Unidade do Cliente <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_cliente_unidade", "disabled" => "true", "size" => 150, "class" => "form-control", "id" => "lid_cliente_unidade", "placeholder" => "Unidade do Cliente"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_cliente_unidade", "size" => 150, "class" => "form-control", "id" => "id_cliente_unidade"]) ?>
                                </div>
                                <div class="form-group col-md-3 botoes_forms_alinhamento">
                                    <label for="designacao_anterior">Designação Anterior</label>
                                    <?php echo $this->tag->textField(["designacao_anterior", "size" => 60, "class" => "form-control", "id" => "designacao_anterior", "placeholder" => "Designação Anterior"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <!--                                    <label for="id_cidadedigital">Cidade Digital <span class="required">*</span></label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_cidadedigital", $cidadedigital, "class" => "form-control", "id" => "id_cidadedigital",
                                    //                                        "using" => ["id", "descricao",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione a Cidade Digital",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_cidadedigital">Cidade Digital <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_cidadedigital", "size" => 60, "class" => "form-control", "id" => "lid_cidadedigital", "placeholder" => "Cidade Digital"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_cidadedigital", "size" => 60, "class" => "form-control", "id" => "id_cidadedigital"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <!--                                    <label for="id_conectividade">Conectividade <span class="required">*</span></label>-->
                                    <!--                                    <select disabled name="id_conectividade" id="id_conectividade" class="form-control">-->
                                    <!--                                        <option value="">Selecione uma Conectividade</option>-->
                                    <!--                                    </select>-->
                                    <label for="lid_conectividade">Conectividade <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_conectividade", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_conectividade", "placeholder" => "Conectividade"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_conectividade", "size" => 60, "class" => "form-control", "id" => "id_conectividade"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_contrato">Contrato <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_contrato", $usacontrato, "class" => "form-control", "id" => "id_contrato",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Contrato",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_tipolink">Tipo Link <span class="required">*</span></label> <!-- Antigo tipo unidade -->
                                    <?php echo $this->tag->select(["id_tipolink", $tipolink, "class" => "form-control", "id" => "id_tipolink",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Link",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="id_funcao">Função <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_funcao", $funcao, "class" => "form-control", "id" => "id_funcao",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Função",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_tipoacesso">Tipo Acesso <span class="required">*</span></label> <!-- Antigo enlace -->
                                    <?php echo $this->tag->select(["id_tipoacesso", $tipoacesso, "class" => "form-control", "id" => "id_tipoacesso",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Acesso",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3 botoes_forms_alinhamento">
                                    <label for="lnumero_serie">Número de Série / Patrimônio</label>
                                    <?php echo $this->tag->textField(["lnumero_serie", "size" => 60, "class" => "form-control", "id" => "lnumero_serie", "placeholder" => "Número de Série / Patrimônio"]) ?>
                                    <?php echo $this->tag->hiddenField(["numero_serie", "size" => 60, "class" => "form-control", "id" => "numero_serie"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="lid_fabricante">Fabricante <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_fabricante", "size" => 150, "class" => "form-control", "id" => "lid_fabricante", "placeholder" => "Fabricante"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_fabricante", "size" => 150, "class" => "form-control", "id" => "id_fabricante"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="lid_modelo">Modelo <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_modelo", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_modelo", "placeholder" => "Modelo"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_modelo", "size" => 60, "class" => "form-control", "id" => "id_modelo"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="lid_equipamento">Equipamento <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_equipamento", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_equipamento", "placeholder" => "Equipamento"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_equipamento", "size" => 60, "class" => "form-control", "id" => "id_equipamento"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="ip_redelocal">Rede Cliente <span class="required">*</span></label> <!-- Antigo IP Rede Local -->
                                    <?php echo $this->tag->textField(["ip_redelocal", "size" => 30, "class" => "form-control ip2", "id" => "ip_redelocal", "placeholder" => "Rede Cliente"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="ip_gerencia">IP de Gerência <span class="required">*</span></label> <!-- Antigo IP Rede Gerencial -->
                                    <?php echo $this->tag->textField(["ip_gerencia", "size" => 30, "class" => "form-control ip", "id" => "ip_gerencia", "placeholder" => "IP de Gerência"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="banda">Banda <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["banda", $banda, "class" => "form-control", "id" => "banda",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Banda",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="tag">TAG <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["tag", "size" => 120, "class" => "form-control", "id" => "tag", "placeholder" => "TAG"]) ?>
                                </div>
                                <div class="form-group col-md-3 botoes_forms_alinhamento">
                                    <label for="ssid">SSID</label> <!-- Antigo ccode -->
                                    <?php echo $this->tag->textField(["ssid", "size" => 30, "class" => "form-control", "id" => "ssid", "placeholder" => "SSID"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="chamado">Chamado <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["chamado", "size" => 120, "class" => "form-control", "id" => "chamado", "placeholder" => "Chamado"]) ?>
                                </div>
                                <div class="form-group col-md-3 botoes_forms_alinhamento">
                                    <label for="data_desinstalacao">Data de Desinstalação </label>
                                    <?php echo $this->tag->textField(["data_desinstalacao", "size" => 120, "class" => "form-control data", "id" => "data_desinstalacao", "placeholder" => "Data de Desinstalação"]) ?>
                                </div>
                                <div class="form-group col-md-3 botoes_forms_alinhamento">
                                    <label for="id_empresa_departamento">Departamento </label>
                                    <?php echo $this->tag->select(["id_empresa_departamento", $departamentos, "class" => "form-control", "id" => "id_empresa_departamento",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o Departamento",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="observacao">Observação</label>
                                    <?php echo $this->tag->textArea(["observacao", "size" => 400, "class" => "form-control", "id" => "observacao", "placeholder" => "Observação"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModal()" data-dismiss="modal">Fechar</button>
                        <button id="salvaCircuitos" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal Visualizar -->
<div id="modalvisualizar" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalvisualizar" aria-hidden="true"
     style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalvisualizar">Visualizar Circuito</h5>
            </div>
            <form id="formVisualizar">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>">
                <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="id_statusv">Status</label>
                                    <?php echo $this->tag->select(["id_statusv", $statuscircuito, "disabled" => "true", "class" => "form-control", "id" => "id_statusv",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Status",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="dtativacaov">Data Ativação</label>
                                    <?php echo $this->tag->textField(["dtativacaov", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "dtativacaov", "placeholder" => "Data Ativação"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="dtatualizacaov">Data Atualização</label>
                                    <?php echo $this->tag->textField(["dtatualizacaov", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "dtatualizacaov", "placeholder" => "Data Atualização"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <!--                                    <label for="id_cliente">Cliente</label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_clientev", $clientes, "disabled" => "true", "class" => "form-control", "id" => "id_clientev",
                                    //                                        "using" => ["id", "nome",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione um Cliente",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_clientev">Cliente <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_clientev", "size" => 150, "disabled" => "true", "class" => "form-control", "id" => "lid_clientev", "placeholder" => "Cliente"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_clientev", "size" => 150, "class" => "form-control", "id" => "id_clientev"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <!--                                    <label for="id_cliente_unidadev">Cliente Unidade</label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_cliente_unidadev", $unidades, "disabled" => "true", "class" => "form-control", "id" => "id_cliente_unidadev",
                                    //                                        "using" => ["id", "nome",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione uma Unidade",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_cliente_unidadev">Cliente Unidade <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_cliente_unidadev", "size" => 150, "disabled" => "true", "class" => "form-control", "id" => "lid_cliente_unidadev", "placeholder" => "Cliente Unidade"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_cliente_unidadev", "size" => 150, "class" => "form-control", "id" => "id_cliente_unidadev"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="designacaov">Designação</label>
                                    <?php echo $this->tag->textField(["designacaov", "size" => 60, "readonly" => "true", "class" => "form-control", "id" => "designacaov", "placeholder" => "Designação"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <!--                                    <label for="id_cidadedigitalv">Cidade Digital <span class="required">*</span></label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_cidadedigitalv", $cidadedigital, "disabled" => "true", "class" => "form-control", "id" => "id_cidadedigitalv",
                                    //                                        "using" => ["id", "descricao",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione a Cidade Digital",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_cidadedigitalv">Cidade Digital <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_cidadedigitalv", "size" => 150, "disabled" => "true", "class" => "form-control", "id" => "lid_cidadedigitalv", "placeholder" => "Cidade Digital"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_cidadedigitalv", "size" => 150, "class" => "form-control", "id" => "id_cidadedigitalv"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <!--                                    <label for="id_conectividadev">Conectividade <span class="required">*</span></label>-->
                                    <!--                                    <select disabled name="id_conectividadev" id="id_conectividadev" class="form-control">-->
                                    <!--                                        <option value="">Selecione uma Conectividade</option>-->
                                    <!--                                    </select>-->
                                    <label for="lid_conectividadev">Conectividade <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_conectividadev", "size" => 150, "disabled" => "true", "class" => "form-control", "id" => "lid_conectividadev", "placeholder" => "Conectividade"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_conectividadev", "size" => 150, "class" => "form-control", "id" => "id_conectividadev"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="id_contratov">Contrato</label>
                                    <?php echo $this->tag->select(["id_contratov", $usacontrato, "disabled" => "true", "class" => "form-control", "id" => "id_contratov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Contrato",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_tipolinkv">Tipo Link</label> <!-- Antigo tipo unidade -->
                                    <?php echo $this->tag->select(["id_tipolinkv", $tipolink, "disabled" => "true", "class" => "form-control", "id" => "id_tipolinkv",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Link",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_funcaov">Função</label>
                                    <?php echo $this->tag->select(["id_funcaov", $funcao, "disabled" => "true", "class" => "form-control", "id" => "id_funcaov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Função",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_tipoacessov">Tipo Acesso</label> <!-- Antigo enlace -->
                                    <?php echo $this->tag->select(["id_tipoacessov", $tipoacesso, "disabled" => "true", "class" => "form-control", "id" => "id_tipoacessov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Acesso",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <!--                                    <label for="id_fabricantev">Fabricante</label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_fabricantev", $fabricantes, "disabled" => "true", "class" => "form-control", "id" => "id_fabricantev",
                                    //                                        "using" => ["id", "nome",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione um Fabricante",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_fabricantev">Fabricante <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_fabricantev", "size" => 150, "disabled" => "true", "class" => "form-control", "id" => "lid_fabricantev", "placeholder" => "Fabricante"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_fabricantev", "size" => 150, "class" => "form-control", "id" => "id_fabricantev"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <!--                                    <label for="id_modelov">Modelo</label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_modelov", $modelos, "disabled" => "true", "class" => "form-control", "id" => "id_modelov",
                                    //                                        "using" => ["id", "modelo",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione um Modelo",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_modelov">Modelo <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_modelov", "size" => 150, "disabled" => "true", "class" => "form-control", "id" => "lid_modelov", "placeholder" => "Modelo"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_modelov", "size" => 150, "class" => "form-control", "id" => "id_modelov"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <!--                                    <label for="id_equipamentov">Equipamento</label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_equipamentov", $equipamentos, "disabled" => "true", "class" => "form-control", "id" => "id_equipamentov",
                                    //                                        "using" => ["id", "nome",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione um Equipamento",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_equipamentov">Equipamento <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_equipamentov", "size" => 150, "disabled" => "true", "class" => "form-control", "id" => "lid_equipamentov", "placeholder" => "Equipamento"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_equipamentov", "size" => 150, "class" => "form-control", "id" => "id_equipamentov"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="numpatserv">Nº Patrimônio / Nº Série</label>
                                    <?php echo $this->tag->textField(["numpatserv", "size" => 80, "readonly" => "true", "class" => "form-control", "id" => "numpatserv", "placeholder" => "Nº Patrimônio / Nº Série"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="ip_redelocalv">Rede Cliente</label> <!-- Antigo IP Rede Local -->
                                    <?php echo $this->tag->textField(["ip_redelocalv", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "ip_redelocalv", "placeholder" => "IP Rede Local"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="ip_gerenciav">IP de Gerência</label> <!-- Antigo IP Rede Gerencial -->
                                    <?php echo $this->tag->textField(["ip_gerenciav", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "ip_gerenciav", "placeholder" => "IP Rede Gerencial"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="bandav">Banda</label>
                                    <?php echo $this->tag->select(["bandav", $banda, "disabled" => "true", "class" => "form-control", "id" => "bandav",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Banda",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="tagv">TAG</label>
                                    <?php echo $this->tag->textField(["tagv", "size" => 120, "readonly" => "true", "class" => "form-control", "id" => "tagv", "placeholder" => "TAG"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="ssidv">SSID</label> <!-- Antigo ccode -->
                                    <?php echo $this->tag->textField(["ssidv", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "ssidv", "placeholder" => "SSID"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="designacao_anteriorv">Designação Anterior</label>
                                    <?php echo $this->tag->textField(["designacao_anteriorv", "size" => 60, "readonly" => "true", "class" => "form-control", "id" => "designacao_anteriorv", "placeholder" => "Designação Anterior"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="chamadov">Chamado</label>
                                    <?php echo $this->tag->textField(["chamadov", "size" => 120, "readonly" => "true", "class" => "form-control", "id" => "chamadov", "placeholder" => "Chamado"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="data_desinstalacaov">Data de Desinstalação </label>
                                    <?php echo $this->tag->textField(["data_desinstalacaov", "size" => 120, "readonly" => "true", "class" => "form-control data", "id" => "data_desinstalacaov", "placeholder" => "Data de Desinstalação"]) ?>
                                </div>
                                <div class="form-group col-md-3 botoes_forms_alinhamento">
                                    <label for="id_empresa_departamentov">Departamento </label>
                                    <?php echo $this->tag->select(["id_empresa_departamentov", $departamentos, "disabled" => "true", "class" => "form-control", "id" => "id_empresa_departamentov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o Departamento",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="observacaov">Observação</label>
                                    <?php echo $this->tag->textArea(["observacaov", "size" => 400, "readonly" => "true", "class" => "form-control", "id" => "observacaov", "placeholder" => "Observação"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <table id="tb_endereco" class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th colspan="4" style="text-align: center;">Endereço do Circuito</th>
                                        </tr>
                                        <tr>
                                            <th>Endereço</th>
                                            <th>Complemento</th>
                                            <th>Bairro</th>
                                            <th>CEP</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <table id="tb_contatos" class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th colspan="5" style="text-align: center;">Contatos para o Circuito</th>
                                        </tr>
                                        <tr>
                                            <th>Principal</th>
                                            <th>Tipo Contato</th>
                                            <th>Nome Contato</th>
                                            <th>Telefone Contato</th>
                                            <th>E-mail Contato</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <table id="tb_movimento" class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th colspan="7" style="text-align: center;">Histórico de Movimentos do Circuito</th>
                                        </tr>
                                        <tr>
                                            <th>OS</th>
                                            <th>Data Movimento</th>
                                            <th>Tipo Movimento</th>
                                            <th>Usuário</th>
                                            <th>Valor Anterior</th>
                                            <th>Valor Atual</th>
                                            <th>Observação</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="idv" name="idv" value=""><!-- Manter como hidden -->
                    <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModal()" data-dismiss="modal">Fechar</button>
                    <button id="pdfCircuito" type="button" class="btn btn-primary btn-rounded waves-effect waves-light">Gerar PDF</button>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal Movimento -->
<div id="modalcircuitosmov" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalcircuitosmov" aria-hidden="true"
     style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalcircuitosmov">Dados do Movimento</h5>
            </div>
            <form id="formCircuitosmov">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>">
                <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <input type="hidden" id="id_circuito" name="id_circuito" value=""><!-- Manter como hidden -->
                                    <label for="id_tipomovimento">Tipo de Movimento <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_tipomovimento", $tipomovimento, "class" => "form-control", "id" => "id_tipomovimento",
                                        "using" => ["valor", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um tipo",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-4 botoes_forms_alinhamento">
                                    <label for="osocomon">Chamado</label>
                                    <?php echo $this->tag->textField(["osocomon", "size" => 60, "class" => "form-control", "id" => "osocomon", "placeholder" => "Chamado"]) ?>
                                </div>
                                <div id="bandamovdiv" class="form-group col-md-4 botoes_forms_alinhamento" style="display: none;">
                                    <label for="bandamov">Banda</label>
                                    <?php echo $this->tag->select(["bandamov", $banda, "class" => "form-control", "id" => "bandamov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Banda",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div id="redelocalmovdiv" class="form-group col-md-4" style="display: none;">
                                    <label for="ip_redelocalmov">Rede Cliente <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["ip_redelocalmov", "size" => 30, "class" => "form-control ip2", "id" => "ip_redelocalmov", "placeholder" => "Rede Cliente"]) ?>
                                </div>
                                <div id="gerenciamovdiv" class="form-group col-md-4" style="display: none;">
                                    <label for="ip_gerenciamov">IP de Gerência <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["ip_gerenciamov", "size" => 30, "class" => "form-control ip", "id" => "ip_gerenciamov", "placeholder" => "IP de Gerência"]) ?>
                                </div>
                                <div id="statusmovdiv" class="form-group col-md-4" style="display: none;">
                                    <label for="id_statusmov">Status <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_statusmov", $statuscircuito, "class" => "form-control", "id" => "id_statusmov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Status",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-4 equip botoes_forms_alinhamento" style="display: none;">
                                    <label for="lnumero_seriemov">Número de Série / Patrimônio</label>
                                    <?php echo $this->tag->textField(["lnumero_seriemov", "size" => 60, "class" => "form-control", "id" => "lnumero_seriemov", "placeholder" => "Número de Série / Patrimônio"]) ?>
                                    <?php echo $this->tag->hiddenField(["numero_seriemov", "size" => 60, "class" => "form-control", "id" => "numero_seriemov"]) ?>
                                </div>
                                <div class="form-group col-md-4 equip" style="display: none;">
                                    <!--                                    <label for="id_fabricantemov">Fabricante <span class="required">*</span></label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_fabricantemov", $fabricantes, "class" => "form-control", "id" => "id_fabricantemov",
                                    //                                        "using" => ["id", "nome",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione um Fabricante",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_fabricantemov">Fabricante <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_fabricantemov", "size" => 60, "class" => "form-control", "id" => "lid_fabricantemov", "placeholder" => "Fabricante"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_fabricantemov", "size" => 60, "class" => "form-control", "id" => "id_fabricantemov"]) ?>
                                </div>
                                <div class="form-group col-md-4 equip" style="display: none;">
                                    <!--                                    <label for="id_modelomov">Modelo <span class="required">*</span></label>-->
                                    <!--                                    <select disabled name="id_modelomov" id="id_modelomov" class="form-control">-->
                                    <!--                                        <option value="">Selecione um Modelo</option>-->
                                    <!--                                    </select>-->
                                    <label for="lid_equipamentomov">Modelo <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_modelomov", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_modelomov", "placeholder" => "Modelo"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_modelomov", "size" => 60, "class" => "form-control", "id" => "id_modelomov"]) ?>
                                </div>
                                <div class="form-group col-md-4 equip" style="display: none;">
                                    <!--                                    <label for="id_equipamentomov">Equipamento <span class="required">*</span></label>-->
                                    <!--                                    <select disabled name="id_equipamentomov" id="id_equipamentomov" class="form-control">-->
                                    <!--                                        <option value="">Selecione um Equipamento</option>-->
                                    <!--                                    </select>-->
                                    <label for="lid_equipamentomov">Equipamento <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_equipamentomov", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_equipamentomov", "placeholder" => "Equipamento"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_equipamentomov", "size" => 60, "class" => "form-control", "id" => "id_equipamentomov"]) ?>
                                </div>
                                <div class="form-group col-md-4 cliente" style="display: none;">
                                    <input type="hidden" id="tipoclientemov" name="tipoclientemov" value=""><!-- Manter como hidden -->
                                    <!--                                    <label for="id_cliente">Cliente <span class="required">*</span></label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_cliente", $clientes, "class" => "form-control", "id" => "id_cliente",
                                    //                                        "using" => ["id", "nome",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione um Cliente",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_clientemov">Cliente <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_clientemov", "size" => 150, "class" => "form-control", "id" => "lid_clientemov", "placeholder" => "Cliente"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_clientemov", "size" => 150, "class" => "form-control", "id" => "id_clientemov"]) ?>
                                </div>
                                <div class="form-group col-md-4 ucliente" style="display: none;">
                                    <!--                                    <label for="id_cliente_unidade">Unidade do Cliente <span class="required">*</span></label>-->
                                    <!--                                    <select disabled name="id_cliente_unidade" id="id_cliente_unidade" class="form-control">-->
                                    <!--                                        <option value="">Selecione uma Unidade</option>-->
                                    <!--                                    </select>-->
                                    <label for="lid_cliente_unidademov">Unidade do Cliente <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_cliente_unidademov", "disabled" => "true", "size" => 150, "class" => "form-control", "id" => "lid_cliente_unidademov", "placeholder" => "Unidade do Cliente"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_cliente_unidademov", "size" => 150, "class" => "form-control", "id" => "id_cliente_unidademov"]) ?>
                                </div>

                                <div class="form-group col-md-4 cidade_digital" style="display: none;">
                                    <!--                                    <label for="id_cidadedigital">Cidade Digital <span class="required">*</span></label>-->
                                    <!--                                    --><?php //echo $this->tag->select(["id_cidadedigital", $cidadedigital, "class" => "form-control", "id" => "id_cidadedigital",
                                    //                                        "using" => ["id", "descricao",],
                                    //                                        "useEmpty" => true,
                                    //                                        "emptyText" => "Selecione a Cidade Digital",
                                    //                                        "emptyValue" => ""])
                                    //                                    ?>
                                    <label for="lid_cidadedigitalmov">Cidade Digital <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_cidadedigitalmov", "size" => 60, "class" => "form-control", "id" => "lid_cidadedigitalmov", "placeholder" => "Cidade Digital"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_cidadedigitalmov", "size" => 60, "class" => "form-control", "id" => "id_cidadedigitalmov"]) ?>
                                </div>
                                <div class="form-group col-md-4 conectividade" style="display: none;">
                                    <!--                                    <label for="id_conectividade">Conectividade <span class="required">*</span></label>-->
                                    <!--                                    <select disabled name="id_conectividade" id="id_conectividade" class="form-control">-->
                                    <!--                                        <option value="">Selecione uma Conectividade</option>-->
                                    <!--                                    </select>-->
                                    <label for="lid_conectividademov">Conectividade <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_conectividademov", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_conectividademov", "placeholder" => "Conectividade"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_conectividademov", "size" => 60, "class" => "form-control", "id" => "id_conectividademov"]) ?>
                                </div>

                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="observacaomov">Observação</label>
                                    <?php echo $this->tag->textArea(["observacaomov", "size" => 400, "class" => "form-control", "id" => "observacaomov", "placeholder" => "Observação"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="idmov" name="idmov" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModal()" data-dismiss="modal">Fechar</button>
                        <button disabled id="salvaCircuitosmov" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal Upload de Anexos -->
<div id="modalanexoscircuitos" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalanexoscircuitos" aria-hidden="true"
     style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalanexoscircuitos">Upload de Anexos para o Circuito de Designação Nº.: <span id="designacao_circuito_anexo"></span></h5>
            </div>
            <form class="fileupload" enctype="multipart/form-data" action="upload" method="POST" id="formAnexosCircuitos">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>">
                <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <div id="dropzone">Arraste e solte os arquivos aqui!</div>
                                </div>
                                <div class="form-group col-md-12">
                                    <input type="file" id="id_file" name="files[]" class="inputfile inputfile-1" data-multiple-caption="{count} arquivos selecionados" multiple/>
                                    <label for="id_file"><span>Escolher Arquivos</span></label>
                                </div>
                            </div>
                            <!-- The table listing the files available for upload/download -->
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <table id="fileTable" style="display: none;" class="table table-striped">
                                        <thead>
                                        <tr><th class="tdth_class">Arquivo</th><th>Tamanho</th><th>Tipo</th><th>Descrição</th><th>Ação Individual</th></tr>
                                        </thead>
                                        <tbody id="fileList">

                                        </tbody>
                                        <tfoot><tr><td id="result"></td><td>&nbsp</td><td>&nbsp</td></tr></tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <!--                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>-->
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id_anexocircuito" name="id_anexocircuito" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModalAnexos()" data-dismiss="modal">Fechar</button>
                        <button id="cancel" type="reset" class="btn btn-danger btn-rounded waves-effect waves-light">Cancelar</button>
                        <button id="salvaAnexosCircuitos" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Upload</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->