<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Phalcon\Tag;
use Util\Util;

?>

<?php echo $this->getContent(); ?>

<div class="col-12">
    <?php
    echo $this->tag->form(
        [
            "circuitos/index",
            "autocomplete" => "off"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldIdCliente" class="col-sm-2 control-label">Cliente</label>
            <div class="col-sm-10">
                <?php echo $this->tag->select(["id_cliente", $clientes, "class" => "form-control", "id" => "fieldIdCliente",
                    "using" => ["id", "nome",],
                    "useEmpty" => true,
                    "emptyText" => "Selecione um Cliente",
                    "emptyValue" => ""])
                ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <label for="fieldIdBanda" class="col-sm-2 control-label">Banda</label>
            <div class="col-sm-10">
                <?php echo $this->tag->select(["id_banda", $banda, "class" => "form-control", "id" => "fieldIdBanda",
                    "using" => ["id", "descricao",],
                    "useEmpty" => true,
                    "emptyText" => "Selecione a Banda",
                    "emptyValue" => ""])
                ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <label for="fieldIdFuncao" class="col-sm-2 control-label">Função</label>
            <div class="col-sm-10">
                <?php echo $this->tag->select(["id_funcao", $funcao, "class" => "form-control", "id" => "fieldIdFuncao",
                    "using" => ["id", "descricao",],
                    "useEmpty" => true,
                    "emptyText" => "Selecione a Função",
                    "emptyValue" => ""])
                ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <label for="fieldIdTipolink" class="col-sm-10 control-label">Tipo Link</label>
            <div class="col-sm-10">
                <?php echo $this->tag->select(["id_tipolink", $tipolink, "class" => "form-control", "id" => "fieldIdTipolink",
                    "using" => ["id", "descricao",],
                    "useEmpty" => true,
                    "emptyText" => "Selecione o Tipo de Acesso",
                    "emptyValue" => ""])
                ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <label for="fieldIdStatus" class="col-sm-2 control-label">Status</label>
            <div class="col-sm-10">
                <?php echo $this->tag->select(["id_status", $statuscircuito, "class" => "form-control", "id" => "fieldIdStatus",
                    "using" => ["id", "descricao",],
                    "useEmpty" => true,
                    "emptyText" => "Selecione um Status",
                    "emptyValue" => ""])
                ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <div class="bt_menu_tabela">
                <?php echo $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldDesignacao" class="col-sm-2 control-label">Designação</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["designacao", "size" => 30, "class" => "form-control", "id" => "fieldDesignacao"]) ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <label for="fieldDesignacaoAnterior" class="col-sm-10 control-label">Designação Anterior</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["designacao_anterior", "size" => 30, "class" => "form-control", "id" => "fieldDesignacaoAnterior"]) ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <label for="fieldIpGerencia" class="col-sm-10 control-label">IP de Gerência</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["ip_gerencia", "size" => 30, "class" => "form-control ip", "id" => "fieldIpGerencia"]) ?>
            </div>
        </div>
        <div class="form-group col-md-2">
            <label for="fieldIpRedelocal" class="col-sm-10 control-label">Rede Cliente (IP)</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["ip_redelocal", "size" => 30, "class" => "form-control ip2", "id" => "fieldIpRedelocal"]) ?>
            </div>
        </div>
    </div>
    <?php echo $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="tb_circuitos" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th style="display: none;">Código</th>
                    <th>Designação</th>
                    <th>Cliente</th>
                    <th>Unidade</th>
                    <th>Cidade</th>
                    <th>Tipo de Link</th>
                    <th>IP de Gerência</th>
                    <th>Função</th>
                    <th>Tipo Acesso</th>
                    <th>Banda</th>
<!--                    <th>Data Cadastro</th>-->
<!--                    <th>Data Atualização</th>-->
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($page->items as $circuitos): ?>
                <?php            
                    $util = new Util();
    //                $data_cadastro = ($circuitos->data_ativacao) ? $util->converterDataHoraParaBr($circuitos->data_ativacao) : null;
    //                $data_atualizacao = ($circuitos->data_atualizacao) ? $util->converterDataHoraParaBr($circuitos->data_atualizacao) : null;
                    switch($circuitos->Cliente->id_tipocliente)
                    {
                        case "44"://Pessoa Física
                            $unidade = null;
                        break;
                        case "43"://Pessoa Jurídica
                            $unidade = $circuitos->ClienteUnidade->Pessoa->nome;
                        break;
                    }
                    $desc_tipolink = ($circuitos->id_tipolink) ? $circuitos->Lov6->descricao : "Campo Obrigatório";
                    $desc_funcao = ($circuitos->id_funcao) ? $circuitos->Lov5->descricao : "Campo Obrigatório";
                    $desc_tipoacesso = ($circuitos->id_tipoacesso) ? $circuitos->Lov4->descricao : "Campo Obrigatório";
                    $desc_banda = ($circuitos->id_banda) ? $circuitos->Lov7->descricao : "Campo Obrigatório";
                    $color_tipolink = (!$circuitos->id_tipolink) ? "style='font-weight: bold; color: red;'" : null;
                    $color_funcao = (!$circuitos->id_funcao) ? "style='font-weight: bold; color: red;'" : null;
                    $color_tipoacesso = (!$circuitos->id_tipoacesso) ? "style='font-weight: bold; color: red;'" : null;
                    $color_banda = (!$circuitos->id_banda) ? "style='font-weight: bold; color: red;'" : null;
                    $cidade = ($circuitos->CidadeDigital->EndCidade->cidade) ? $circuitos->CidadeDigital->EndCidade->cidade : null;
                ?>
                <tr>
                    <td style="display: none;">
                        <?php echo $circuitos->id ?>
                    </td>
                    <td>
                        <?php echo $circuitos->designacao ?>
                    </td>
                    <td>
                        <?php echo $circuitos->Cliente->Pessoa->nome ?>
                    </td>
                    <td>
                        <?php echo $unidade ?>
                    </td>
                    <td>
                        <?php echo $cidade ?>
                    </td>
                    <td <?php echo $color_tipolink ?>>
                        <?php echo $desc_tipolink ?>
                    </td>
                    <td>
                        <?php echo $circuitos->ip_gerencia ?>
                    </td>
                    <td <?php echo $color_funcao ?>>
                        <?php echo $desc_funcao ?>
                    </td>
                    <td <?php echo $color_tipoacesso ?>>
                        <?php echo $desc_tipoacesso ?>
                    </td>
                    <td <?php echo $color_banda ?>>
                        <?php echo $desc_banda ?>
                    </td>
<!--                    <td>-->
<!--                        --><?php //echo $data_cadastro ?>
<!--                    </td>-->
<!--                    <td>-->
<!--                        --><?php //echo $data_atualizacao ?>
<!--                    </td>-->
                    <td>
                        <?php echo $circuitos->Lov2->descricao ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<!--  Modal Circuitos -->
<div id="modalcircuitos" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalcircuitos" aria-hidden="true"
    style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalcircuitos">Dados do Circuito</h5>
            </div>
            <form id="formCircuitos">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>">
                <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <input type="hidden" id="tipocliente" name="tipocliente" value=""><!-- Manter como hidden -->
                                    <label for="id_cliente">Cliente <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_cliente", $clientes, "class" => "form-control", "id" => "id_cliente",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Cliente",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_cliente_unidade">Unidade do Cliente <span class="required">*</span></label>
                                    <select disabled name="id_cliente_unidade" id="id_cliente_unidade" class="form-control">
                                        <option value="">Selecione uma Unidade</option>
                                    </select>
                                </div>
                                <!-- Designação
                                <div class="form-group col-md-3">
                                    <label for="designacao">Designação <span class="required">*</span></label>
                                    <?php //echo $this->tag->textField(["designacao", "size" => 60, "class" => "form-control", "readonly" => "true", "id" => "designacao", "placeholder" => "Designação"]) ?>
                                </div> -->
                                <div class="form-group col-md-3">
                                    <label for="designacao_anterior">Designação Anterior</label>
                                    <?php echo $this->tag->textField(["designacao_anterior", "size" => 60, "class" => "form-control", "id" => "designacao_anterior", "placeholder" => "Designação Anterior"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_cidadedigital">Cidade Digital <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_cidadedigital", $cidadedigital, "class" => "form-control", "id" => "id_cidadedigital",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Cidade Digital",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="id_contrato">Contrato <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_contrato", $usacontrato, "class" => "form-control", "id" => "id_contrato",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Contrato",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_cluster">Cluster <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_cluster", $cluster, "class" => "form-control", "id" => "id_cluster",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Cluster",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_tipolink">Tipo Link <span class="required">*</span></label> <!-- Antigo tipo unidade -->
                                    <?php echo $this->tag->select(["id_tipolink", $tipolink, "class" => "form-control", "id" => "id_tipolink",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Link",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_funcao">Função <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_funcao", $funcao, "class" => "form-control", "id" => "id_funcao",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Função",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="id_tipoacesso">Tipo Acesso <span class="required">*</span></label> <!-- Antigo enlace -->
                                    <?php echo $this->tag->select(["id_tipoacesso", $tipoacesso, "class" => "form-control", "id" => "id_tipoacesso",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Acesso",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_fabricante">Fabricante <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_fabricante", $fabricantes, "class" => "form-control", "id" => "id_fabricante",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Fabricante",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
<!--                                    <label for="id_modelo">Modelo <span class="required">*</span></label>-->
<!--                                    <select disabled name="id_modelo" id="id_modelo" class="form-control">-->
<!--                                        <option value="">Selecione um Modelo</option>-->
<!--                                    </select>-->
                                    <label for="lid_modelo">Modelo <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_modelo", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_modelo", "placeholder" => "Modelo"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_modelo", "size" => 60, "class" => "form-control", "id" => "id_modelo"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <!--
                                    <label for="id_equipamento">Equipamento <span class="required">*</span></label>
                                    <select disabled name="id_equipamento" id="id_equipamento" class="form-control">
                                        <option value="">Selecione um Equipamento</option>
                                    </select> -->
                                    <label for="lid_equipamento">Equipamento <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_equipamento", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_equipamento", "placeholder" => "Equipamento"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_equipamento", "size" => 60, "class" => "form-control", "id" => "id_equipamento"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="ip_redelocal">Rede Cliente <span class="required">*</span></label> <!-- Antigo IP Rede Local -->
                                    <?php echo $this->tag->textField(["ip_redelocal", "size" => 30, "class" => "form-control ip2", "id" => "ip_redelocal", "placeholder" => "Rede Cliente"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="ip_gerencia">IP de Gerência <span class="required">*</span></label> <!-- Antigo IP Rede Gerencial -->
                                    <?php echo $this->tag->textField(["ip_gerencia", "size" => 30, "class" => "form-control ip", "id" => "ip_gerencia", "placeholder" => "IP de Gerência"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="banda">Banda <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["banda", $banda, "class" => "form-control", "id" => "banda",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Banda",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="tag">TAG <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["tag", "size" => 120, "class" => "form-control", "id" => "tag", "placeholder" => "TAG"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="ssid">SSID</label> <!-- Antigo ccode -->
                                    <?php echo $this->tag->textField(["ssid", "size" => 30, "class" => "form-control", "id" => "ssid", "placeholder" => "SSID"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="chamado">Chamado <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["chamado", "size" => 120, "class" => "form-control", "id" => "chamado", "placeholder" => "Chamado"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="observacao">Observação</label>
                                    <?php echo $this->tag->textArea(["observacao", "size" => 400, "class" => "form-control", "id" => "observacao", "placeholder" => "Observação"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModal()" data-dismiss="modal">Fechar</button>
                        <button id="salvaCircuitos" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal Visualizar -->
<div id="modalvisualizar" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalvisualizar" aria-hidden="true"
    style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalvisualizar">Visualizar Circuito</h5>
            </div>
            <form id="formVisualizar">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>">
                <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="id_statusv">Status</label>
                                    <?php echo $this->tag->select(["id_statusv", $statuscircuito, "disabled" => "true", "class" => "form-control", "id" => "id_statusv",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Status",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="dtativacaov">Data Ativação</label>
                                    <?php echo $this->tag->textField(["dtativacaov", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "dtativacaov", "placeholder" => "Data Ativação"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="dtatualizacaov">Data Atualização</label>
                                    <?php echo $this->tag->textField(["dtatualizacaov", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "dtatualizacaov", "placeholder" => "Data Atualização"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_cliente">Cliente</label>
                                    <?php echo $this->tag->select(["id_clientev", $clientes, "disabled" => "true", "class" => "form-control", "id" => "id_clientev",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Cliente",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="id_cliente_unidadev">Cliente Unidade</label>
                                    <?php echo $this->tag->select(["id_cliente_unidadev", $unidades, "disabled" => "true", "class" => "form-control", "id" => "id_cliente_unidadev",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione uma Unidade",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="designacaov">Designação</label>
                                    <?php echo $this->tag->textField(["designacaov", "size" => 60, "readonly" => "true", "class" => "form-control", "id" => "designacaov", "placeholder" => "Designação"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_cidadedigitalv">Cidade Digital</label>
                                    <?php echo $this->tag->select(["id_cidadedigitalv", $cidadedigital, "readonly" => "true", "class" => "form-control", "id" => "id_cidadedigitalv",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Cidade Digital",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_contratov">Contrato</label>
                                    <?php echo $this->tag->select(["id_contratov", $usacontrato, "disabled" => "true", "class" => "form-control", "id" => "id_contratov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Contrato",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="id_clusterv">Cluster</label>
                                    <?php echo $this->tag->select(["id_clusterv", $cluster, "disabled" => "true", "class" => "form-control", "id" => "id_clusterv",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Cluster",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_tipolinkv">Tipo Link</label> <!-- Antigo tipo unidade -->
                                    <?php echo $this->tag->select(["id_tipolinkv", $tipolink, "disabled" => "true", "class" => "form-control", "id" => "id_tipolinkv",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Link",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_funcaov">Função</label>
                                    <?php echo $this->tag->select(["id_funcaov", $funcao, "disabled" => "true", "class" => "form-control", "id" => "id_funcaov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Função",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_tipoacessov">Tipo Acesso</label> <!-- Antigo enlace -->
                                    <?php echo $this->tag->select(["id_tipoacessov", $tipoacesso, "disabled" => "true", "class" => "form-control", "id" => "id_tipoacessov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Acesso",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="id_fabricantev">Fabricante</label>
                                    <?php echo $this->tag->select(["id_fabricantev", $fabricantes, "disabled" => "true", "class" => "form-control", "id" => "id_fabricantev",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Fabricante",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_modelov">Modelo</label>
                                    <?php echo $this->tag->select(["id_modelov", $modelos, "disabled" => "true", "class" => "form-control", "id" => "id_modelov",
                                        "using" => ["id", "modelo",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Modelo",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="id_equipamentov">Equipamento</label>
                                    <?php echo $this->tag->select(["id_equipamentov", $equipamentos, "disabled" => "true", "class" => "form-control", "id" => "id_equipamentov",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Equipamento",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="numpatserv">Nº Patrimônio / Nº Série</label>
                                    <?php echo $this->tag->textField(["numpatserv", "size" => 80, "readonly" => "true", "class" => "form-control", "id" => "numpatserv", "placeholder" => "Nº Patrimônio / Nº Série"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="ip_redelocalv">Rede Cliente</label> <!-- Antigo IP Rede Local -->
                                    <?php echo $this->tag->textField(["ip_redelocalv", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "ip_redelocalv", "placeholder" => "IP Rede Local"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="ip_gerenciav">IP de Gerência</label> <!-- Antigo IP Rede Gerencial -->
                                    <?php echo $this->tag->textField(["ip_gerenciav", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "ip_gerenciav", "placeholder" => "IP Rede Gerencial"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="bandav">Banda</label>
                                    <?php echo $this->tag->select(["bandav", $banda, "disabled" => "true", "class" => "form-control", "id" => "bandav",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Banda",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="tagv">TAG</label>
                                    <?php echo $this->tag->textField(["tagv", "size" => 120, "readonly" => "true", "class" => "form-control", "id" => "tagv", "placeholder" => "TAG"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="ssidv">SSID</label> <!-- Antigo ccode -->
                                    <?php echo $this->tag->textField(["ssidv", "size" => 30, "readonly" => "true", "class" => "form-control", "id" => "ssidv", "placeholder" => "SSID"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="designacao_anteriorv">Designação Anterior</label>
                                    <?php echo $this->tag->textField(["designacao_anteriorv", "size" => 60, "readonly" => "true", "class" => "form-control", "id" => "designacao_anteriorv", "placeholder" => "Designação Anterior"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="chamadov">Chamado</label>
                                    <?php echo $this->tag->textField(["chamadov", "size" => 120, "readonly" => "true", "class" => "form-control", "id" => "chamadov", "placeholder" => "Chamado"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="observacaov">Observação</label>
                                    <?php echo $this->tag->textArea(["observacaov", "size" => 400, "readonly" => "true", "class" => "form-control", "id" => "observacaov", "placeholder" => "Observação"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <table id="tb_movimento" class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th colspan="7" style="text-align: center;">Histórico de Movimentos do Circuito</th>
                                            </tr>
                                            <tr>
                                                <th>OS</th>
                                                <th>Data Movimento</th>
                                                <th>Tipo Movimento</th>
                                                <th>Usuário</th>
                                                <th>Valor Anterior</th>
                                                <th>Valor Atual</th>
                                                <th>Observação</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="idv" name="idv" value=""><!-- Manter como hidden -->
                    <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModal()" data-dismiss="modal">Fechar</button>
                    <button id="pdfCircuito" type="button" class="btn btn-primary btn-rounded waves-effect waves-light">Gerar PDF</button>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal Movimento -->
<div id="modalcircuitosmov" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalcircuitosmov" aria-hidden="true"
    style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalcircuitosmov">Dados do Movimento</h5>
            </div>
            <form id="formCircuitosmov">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>">
                <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <input type="hidden" id="id_circuito" name="id_circuito" value=""><!-- Manter como hidden -->
                                    <label for="id_tipomovimento">Tipo de Movimento <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_tipomovimento", $tipomovimento, "class" => "form-control", "id" => "id_tipomovimento",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um tipo",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="osocomon">Chamado</label>
                                    <?php echo $this->tag->textField(["osocomon", "size" => 60, "class" => "form-control", "id" => "osocomon", "placeholder" => "Chamado"]) ?>
                                </div>
                                <div id="bandamovdiv" class="form-group col-md-4" style="display: none;">
                                    <label for="bandamov">Banda</label>
                                    <?php echo $this->tag->select(["bandamov", $banda, "class" => "form-control", "id" => "bandamov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione a Banda",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div id="redelocalmovdiv" class="form-group col-md-4" style="display: none;">
                                    <label for="ip_redelocalmov">Rede Cliente <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["ip_redelocalmov", "size" => 30, "class" => "form-control ip2", "id" => "ip_redelocalmov", "placeholder" => "Rede Cliente"]) ?>
                                </div>
                                <div id="gerenciamovdiv" class="form-group col-md-4" style="display: none;">
                                    <label for="ip_gerenciamov">IP de Gerência <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["ip_gerenciamov", "size" => 30, "class" => "form-control ip", "id" => "ip_gerenciamov", "placeholder" => "IP de Gerência"]) ?>
                                </div>
                                <div id="statusmovdiv" class="form-group col-md-4" style="display: none;">
                                    <label for="id_statusmov">Status <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_statusmov", $statuscircuito, "class" => "form-control", "id" => "id_statusmov",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Status",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-4 equip" style="display: none;">
                                    <label for="id_fabricantemov">Fabricante <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_fabricantemov", $fabricantes, "class" => "form-control", "id" => "id_fabricantemov",
                                        "using" => ["id", "nome",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um Fabricante",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-4 equip" style="display: none;">
<!--                                    <label for="id_modelomov">Modelo <span class="required">*</span></label>-->
<!--                                    <select disabled name="id_modelomov" id="id_modelomov" class="form-control">-->
<!--                                        <option value="">Selecione um Modelo</option>-->
<!--                                    </select>-->
                                    <label for="lid_equipamentomov">Modelo <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_modelomov", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_modelomov", "placeholder" => "Modelo"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_modelomov", "size" => 60, "class" => "form-control", "id" => "id_modelomov"]) ?>
                                </div>
                                <div class="form-group col-md-4 equip" style="display: none;">
                                    <!--
                                    <label for="id_equipamentomov">Equipamento <span class="required">*</span></label>
                                    <select disabled name="id_equipamentomov" id="id_equipamentomov" class="form-control">
                                        <option value="">Selecione um Equipamento</option>
                                    </select>
                                    -->
                                    <label for="lid_equipamentomov">Equipamento <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_equipamentomov", "disabled" => "true", "size" => 60, "class" => "form-control", "id" => "lid_equipamentomov", "placeholder" => "Equipamento"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_equipamentomov", "size" => 60, "class" => "form-control", "id" => "id_equipamentomov"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="observacaomov">Observação</label>
                                    <?php echo $this->tag->textArea(["observacaomov", "size" => 400, "class" => "form-control", "id" => "observacaomov", "placeholder" => "Observação"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="idmov" name="idmov" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModal()" data-dismiss="modal">Fechar</button>
                        <button disabled id="salvaCircuitosmov" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->