<?php

use Util\Util;

?>

<div class="col-12">
    <div class="card-box">
        <table id="tb_empresa" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Nome</th>
                    <th>CNPJ</th>
                    <th>Dados Servidor E-mail</th>
                    <th>Data Cadastro</th>
                    <th>Data Alteração</th>
                    <th>Ativo</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($page->items as $empresa): ?>
            <?php            
                $util = new Util();
                if ($empresa->Pessoa->PessoaJuridica->cnpj){
                    $cnpj = $util->mask($empresa->Pessoa->PessoaJuridica->cnpj, "##.###.###/####-##");
                } else {
                    $cnpj = null;
                }
                if ($empresa->EmpresaParametros){
                    $config_email = "Sim";
                } else {
                    $config_email = "Não";
                }
                switch($empresa->Pessoa->ativo){
                    case '0'://Inativo (False)
                    $ativo = "Inativo";
                    break;
                    case '1'://Ativo (True)
                    $ativo = "Ativo";
                    break;
                }
            ?>
                    <tr>
                        <td><?php echo $empresa->id ?></td>
                        <td><?php echo $empresa->Pessoa->nome ?></td>
                        <td><?php echo $cnpj ?></td>
                        <td><?php echo $config_email ?></td>
                        <td><?php echo $util->converterDataHoraParaBr($empresa->Pessoa->create_at) ?></td>
                        <td><?php echo $util->converterDataHoraParaBr($empresa->Pessoa->update_at) ?></td>
                        <td><?php echo $ativo ?></td>
                    </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Empresa -->
<div id="modalempresa" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalempresa" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalempresa">Dados da Empresa</h5>
            </div>
            <form id="formEmpresa">
                <input type="hidden" id="token" name="<?php echo $token['tokenKey'] ?>" value="<?php echo $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <h6>Dados Cadastrais</h6>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="nome_pessoa">Nome Fantasia <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["nome_pessoa", "size" => 200, "class" => "form-control", "id" => "nome_pessoa", "placeholder" => "Nome Fantasia"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="razaosocial">Razão Social <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["razaosocial", "size" => 200, "class" => "form-control", "id" => "razaosocial", "placeholder" => "Razão Social"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="cnpj">CNPJ</label>
                                    <?php echo $this->tag->textField(["cnpj", "size" => 30, "class" => "form-control cnpj", "id" => "cnpj", "placeholder" => "CNPJ"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="inscestadual">Inscrição Estadual</label>
                                    <?php echo $this->tag->textField(["inscestadual", "size" => 30, "class" => "form-control", "id" => "inscestadual", "placeholder" => "Inscrição Estadual"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inscmunicipal">Inscrição Municipal</label>
                                    <?php echo $this->tag->textField(["inscmunicipal", "size" => 30, "class" => "form-control", "id" => "inscmunicipal", "placeholder" => "Inscrição Municipal"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="fundacao">Data Fundação</label>
                                    <?php echo $this->tag->textField(["fundacao", "size" => 30, "class" => "form-control data", "id" => "fundacao", "placeholder" => "Data Fundação"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="setor">Setor</label>
                                    <?php echo $this->tag->select(["setor", $setor, "class" => "form-control", "id" => "setor",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione um setor",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="esfera">Esfera</label>
                                    <?php echo $this->tag->select(["esfera", $esfera, "class" => "form-control", "id" => "esfera",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione uma esfera",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="email">E-mail <span class="required">*</span></label>
                                    <?php echo $this->tag->emailField(["email", "size" => 120, "class" => "form-control", "id" => "email", "placeholder" => "E-mail (Aparecerá como remetente dos envios)"]) ?>
                                </div>
                            </div>
                            <h6>Dados do Endereço</h6>
                            <div class="form-row">
                                <input type="hidden" id="sigla_uf" name="sigla_uf" value=""><!-- Manter como hidden -->
                                <div class="form-group col-md-3">
                                    <label for="cep">CEP <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["cep", "size" => 200, "class" => "form-control cep", "id" => "cep", "placeholder" => "CEP"]) ?>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="endereco">Endereço <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["endereco", "size" => 200, "class" => "form-control", "id" => "endereco", "placeholder" => "Endereço"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="numero">Número</label>
                                    <?php echo $this->tag->textField(["numero", "size" => 120, "class" => "form-control", "id" => "numero", "placeholder" => "Número"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-5">
                                    <label for="complemento">Complemento</label>
                                    <?php echo $this->tag->textField(["complemento", "size" => 120, "class" => "form-control", "id" => "complemento", "placeholder" => "Complemento"]) ?>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="bairro">Bairro</label>
                                    <?php echo $this->tag->textField(["bairro", "size" => 120, "class" => "form-control", "id" => "bairro", "placeholder" => "Bairro"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="cidade">Cidade</label>
                                    <?php echo $this->tag->textField(["cidade", "size" => 120, "class" => "form-control", "id" => "cidade", "placeholder" => "Cidade"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="estado">Estado</label>
                                    <?php echo $this->tag->textField(["estado", "size" => 120, "class" => "form-control", "id" => "estado", "placeholder" => "Estado"]) ?>
                                </div>
                            </div>
                            <h6>Dados do Servidor de E-mails (Configura o serviço de envio de mensagens do sistema)</h6>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="mail_host">Endereço do HOST <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["mail_host", "size" => 200, "class" => "form-control", "id" => "mail_host", "placeholder" => "Endereço do HOST"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="mail_port">Porta SMTP <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["mail_port", "size" => 90, "class" => "form-control", "id" => "mail_port", "placeholder" => "Porta SMTP (587, 995, etc)"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="mail_smtpssl">Protolo de Segurança <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["mail_smtpssl", "size" => 90, "class" => "form-control", "id" => "mail_smtpssl", "placeholder" => "Protolo de Segurança (TLS, SSL, etc)"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="mail_user">Usuário a ser utilizado <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["mail_user", "size" => 200, "class" => "form-control", "id" => "mail_user", "placeholder" => "Usuário a ser utilizado"]) ?>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="mail_passwrd">Senha de Acesso <span class="required">*</span></label>
                                    <?php echo $this->tag->passwordField(["mail_passwrd", "size" => 90, "class" => "form-control", "id" => "mail_passwrd", "placeholder" => "Senha de Acesso"]) ?>
                                </div>
                                <!--<div class="form-group col-md-4">
                                    <button id="testa_email" name="testa_email" type="button" class="btn btn-danger btn-rounded waves-light waves-effect w-md">Testar Configurações</button>
                                </div> -->
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group col-md-6">
                            <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                        </div>
                        <div class="form-group col-md-6 botoes_rodape">
                            <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                            <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" data-dismiss="modal">Fechar</button>
                            <button id="salvaEmpresa" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                        </div>
                    </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->