<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Auth\Autentica;
use Phalcon\Tag;
use Util\Infra;

$infra = new Infra();
$auth = new Autentica();
$security_plugin = new SecurityPlugin();
$acl = $security_plugin->getAcl();
$role = $auth->getRoles();
$module = $this->router->getControllerName();

?>

<?= $this->getContent(); ?>

<div class="col-12">
    <?= $this->tag->form(
        [
            "contrato/index",
            "autocomplete" => "off",
            "id" => "formPesquisa"
        ]
    );
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?= $this->tag->textField(["pesquisa", "size" => 60, "class" => "form-control", "id" => "fieldPesquisa"]) ?>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="bt_menu_tabela">
                <?= $this->tag->submitButton(["Pesquisar", "class" => "btn btn-info btn-rounded waves-light w-md"]) ?>
                <button type="button" name="bt_limpar" id="bt_limpar" class="btn btn-warning btn-rounded waves-light w-md" onclick="limpar();">Limpar</button>
                <?php if($acl->isAllowed($role,$module, 'criar')): ?>
                    <button type="button" name="bt_novo" id="bt_novo" class="btn btn-success btn-rounded waves-light w-md" onclick="criar();">Novo</button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?= $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="datatable_listar" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Número</th>
                <th>Cliente/Fornecedor</th>
                <th>Processo Contratação</th>
                <th>Ano</th>
                <th>Valor Global</th>
                <th>Status</th>
                <th>Ativo</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page as $contrato): ?>
                <?php
                switch($contrato->getAtivo())
                {
                    case '0'://Inativo (False)
                        $ativo = "Inativo";
                        $class_tr = 'class="table-danger"';
                        break;
                    case '1'://Ativo (True)
                        $ativo = "Ativo";
                        $class_tr = null;
                        break;
                }
                ?>
                <tr <?= $class_tr; ?>>
                    <td><?= $contrato->getId() ?></td>
                    <td><?= $contrato->getNumero() ?></td>
                    <td><?= $contrato->getCliente() ?></td>
                    <td><?= $contrato->getNumeroProcessoContratacao() ?></td>
                    <td><?= $contrato->getAno() ?></td>
                    <td><?= $contrato->getValorGlobal() ?></td>
                    <td><?= $contrato->getStatus() ?></td>
                    <td><?= $ativo ?></td>
                    <td class="td_acoes">
                        <?php if($acl->isAllowed($role,$module, 'visualizar')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $contrato->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.png" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                        <?php endif; ?>
                        <?php if($contrato->getAtivo() == '0'): ?>
                            <?php if($acl->isAllowed($role, $module, 'ativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="ativar(<?= $contrato->getId() ?>, '<?= $contrato->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.png" title="Ativar" alt="Ativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($acl->isAllowed($role, $module, 'editar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="editar(<?= $contrato->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.png" title="Editar" alt="Editar" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'inativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="inativar(<?= $contrato->getId() ?>, '<?= $contrato->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.png" title="Desativar" alt="Desativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($acl->isAllowed($role, $module, 'excluir')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="excluir(<?= $contrato->getId() ?>, '<?= $contrato->getDescricao() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.png" title="Excluir" alt="Excluir" height="25" width="25"></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Cadastro -->
<div id="modalCadastro" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalCadastro" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="confirmaCancelar('modalCadastro');">×</button>
                <h5 class="modal-title" id="modalCadastro">Dados da Contrato</h5>
            </div>
            <form id="formCadastro">
                <input type="hidden" id="token" name="<?= $token['tokenKey'] ?>" value="<?= $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col-12">
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <label for="vincular_instrumento">Vincular a outro Instrumento? <span class="required">*</span></label>
                                    <select id="vincular_instrumento" name="vincular_instrumento" class="form-control" onchange="vincularContrato();">
                                        <option value="1">Sim</option>
                                        <option value="0" selected>Não</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="lid_contrato_principal">Contrato Principal </label>
                                    <?php echo $this->tag->textField(["lid_contrato_principal", "size" => 120, "disabled" => "true", "class" => "form-control", "id" => "lid_contrato_principal", "placeholder" => "Contrato a ser vinculado", "onkeyup" => "autocompletarContratoVinculado();"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_contrato_principal", "size" => 120, "class" => "form-control", "id" => "id_contrato_principal"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="id_tipo_contrato">Tipo Contrato <span class="required">*</span></label>
                                    <?php echo $this->tag->select(["id_tipo_contrato", $tipos, "class" => "form-control", "id" => "id_tipo_contrato", "onchange" => "contratoClienteFornecedor();",
                                        "using" => ["id", "descricao",],
                                        "useEmpty" => true,
                                        "emptyText" => "Selecione o tipo de Contrato",
                                        "emptyValue" => ""])
                                    ?>
                                </div>
                                <div id="div_fornecedor" class="form-group col-md-4" style="display: none;">
                                    <label for="lid_fornecedor">Fornecedor <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_fornecedor", "size" => 120, "class" => "form-control", "id" => "lid_fornecedor", "placeholder" => "Fornecedor", "onkeyup" => "autocompletarFornecedor();"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_fornecedor", "size" => 120, "class" => "form-control", "id" => "id_fornecedor"]) ?>
                                </div>
                                <div id="div_cliente" class="form-group col-md-4">
                                    <label for="lid_cliente">Cliente <span class="required">*</span></label>
                                    <?php echo $this->tag->textField(["lid_cliente", "size" => 120, "class" => "form-control", "id" => "lid_cliente", "placeholder" => "Cliente", "onkeyup" => "autocompletarCliente();"]) ?>
                                    <?php echo $this->tag->hiddenField(["id_cliente", "size" => 120, "class" => "form-control", "id" => "id_cliente"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <label for="data_criacao">Data de Criação </label>
                                    <?= $this->tag->textField(["data_criacao", "size" => 200, "class" => "form-control data", "id" => "data_criacao", "placeholder" => "Data de Criação de Contrato"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="data_assinatura">Data de Assinatura</label>
                                    <?= $this->tag->textField(["data_assinatura", "size" => 200, "class" => "form-control data", "id" => "data_assinatura", "placeholder" => "Data de Assinatura do Contrato"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="data_publicacao">Data de Publicação </label>
                                    <?= $this->tag->textField(["data_publicacao", "size" => 200, "class" => "form-control data", "id" => "data_publicacao", "placeholder" => "Data de Publicação do Contrato"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="num_diario_oficial">Número Diário Oficial</label>
                                    <?= $this->tag->textField(["num_diario_oficial", "size" => 200, "class" => "form-control", "id" => "num_diario_oficial", "placeholder" => "Número Diário Oficial"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="vigencia_tipo">Tipo de Vigência </label>
                                    <select id="vigencia_tipo" name="vigencia_tipo" class="form-control">
                                        <option value="0">Dia</option>
                                        <option value="1">Mês</option>
                                        <option value="2">Ano</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="vigencia_prazo">Prazo de Vigência</label>
                                    <?= $this->tag->textField(["vigencia_prazo", "size" => 200, "class" => "form-control", "id" => "vigencia_prazo", "placeholder" => "Prazo de Vigência"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <label for="numero">Número </label>
                                    <?= $this->tag->textField(["numero", "size" => 200, "class" => "form-control data", "id" => "numero", "placeholder" => "Número do Contrato"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="ano">Ano</label>
                                    <?= $this->tag->textField(["ano", "size" => 200, "class" => "form-control ano", "id" => "ano", "placeholder" => "Ano do Contrato"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="valor_global">Valor Global </label>
                                    <?= $this->tag->textField(["valor_global", "size" => 200, "class" => "form-control valor_monetario_limpo", "id" => "data_publicacao", "placeholder" => "Valor Global do Contrato"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="exercicio">Exercício</label>
                                    <?= $this->tag->textField(["exercicio", "size" => 200, "class" => "form-control ano", "id" => "exercicio", "placeholder" => "Exercício do Contrato"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="valor_exercicio">Valor do Exercício</label>
                                    <?= $this->tag->textField(["valor_exercicio", "size" => 200, "class" => "form-control valor_monetario_limpo", "id" => "valor_exercicio", "placeholder" => "Valor do Exercício do Contrato"]) ?>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="valor_mensal">Valor Mensal</label>
                                    <?= $this->tag->textField(["valor_mensal", "size" => 200, "class" => "form-control valor_monetario_limpo", "id" => "valor_mensal", "placeholder" => "Valor Mensal do Contrato"]) ?>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <label for="objeto">Objeto</label>
                                    <?php echo $this->tag->textArea(["objeto", "size" => 400, "class" => "form-control", "id" => "objeto", "placeholder" => "Objeto contratual"]) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="confirmaCancelar('modalCadastro');">Fechar</button>
                        <button id="salvarCadastro" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light" onclick="salvar();" value="">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->