<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */

use Auth\Autentica;
use Util\Infra;

$infra = new Infra();
$auth = new Autentica();
$security_plugin = new SecurityPlugin();
$acl = $security_plugin->getAcl();
$role = $auth->getRoles();
$module = $this->router->getControllerName();

?>

<?= $this->getContent(); ?>

<div class="col-12">
    <?= $this->tag->form(
        [
            'contrato_penalidade',
            'autocomplete' => 'off',
            'id' => 'formPesquisa'
        ]
    )
    ?>
    <div class="form-row">
        <div class="form-group col-md-2">
            <label for="fieldPesquisa" class="col-sm-2 control-label">Pesquisa</label>
            <div class="col-sm-10">
                <?= $this->tag->textField(['pesquisa', 'size' => 60, 'class' => 'form-control', 'id' => 'fieldPesquisa']) ?>
            </div>
        </div>
        <div class="form-group col-md-4">
            <div class="bt_menu_tabela">
                <?= $this->tag->submitButton(['Pesquisar', 'class' => 'btn btn-info btn-rounded waves-light w-md']) ?>
                <button type="button" name="bt_limpar" id="bt_limpar" class="btn btn-warning btn-rounded waves-light w-md" onclick="limpar();">Limpar</button>
                <?php if($acl->isAllowed($role,$module, 'criar')): ?>
                    <button type="button" name="bt_novo" id="bt_novo" class="btn btn-success btn-rounded waves-light w-md" onclick="criar();">Novo</button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <?= $this->tag->endForm(); ?>
</div>

<div class="col-12">
    <div class="card-box">
        <table id="datatable_listar" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
            <tr>
                <th>Código</th>
                <th>Contrato</th>
                <th>Status</th>
                <th>Número Processo</th>
                <th>Número Notificação</th>
                <th>Número RT</th>
                <th>Data Criação</th>
                <th>Valor da Multa</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($page as $contratopenalidade): ?>
                <?php
                switch($contratopenalidade->getStatus())
                {
                    case '0'://Aberto
                        $class_tr = null;
                        break;
                    case '1'://Executado
                        $class_tr = 'class="table-success"';
                        break;
                    case '2'://Cancelado
                        $class_tr = 'class="table-danger"';
                        break;
                }
                ?>
                <tr <?= $class_tr ?>>
                    <td><?= $contratopenalidade->getId() ?></td>
                    <td><?= $contratopenalidade->getNumeroAnoContrato() ?></td>
                    <td><?= $contratopenalidade->getStatusDescricao() ?></td>
                    <td><?= $contratopenalidade->getNumeroProcesso() ?></td>
                    <td><?= $contratopenalidade->getNumeroNotificacao() ?></td>
                    <td><?= $contratopenalidade->getNumeroRt() ?></td>
                    <td><?= $contratopenalidade->getDataCriacaoFormatada() ?></td>
                    <td><?= $contratopenalidade->getValorMultaFormatado() ?></td>
                    <td class="td_acoes">
                        <?php if($acl->isAllowed($role,$module, 'visualizar')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $contratopenalidade->getId() ?>, true);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/visualizar.png" title="Visualizar" alt="Visualizar" height="25" width="25"></a>
                        <?php endif; ?>
                        <?php if($contratopenalidade->getAtivo() == '0'): ?>
                            <?php if($acl->isAllowed($role, $module, 'ativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="ativar(<?= $contratopenalidade->getId() ?>, '<?= $contratopenalidade->getNumeroProcesso() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/reativar.png" title="Ativar" alt="Ativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($acl->isAllowed($role, $module, 'movimentar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="criarMovimento(<?= $contratopenalidade->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/movimentar.png" title="Movimentar" alt="Movimentar" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'subir')): ?> <!-- Anexo de Arquivos -->
                                <a href="javascript:void(0)" class="botoes_acao" onclick="criarAnexo(<?= $contratopenalidade->getId() ?>);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/upload.png" title="Anexar Arquivo" alt="Anexar Arquivo" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'editar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="visualizar(<?= $contratopenalidade->getId() ?>, false);"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/editar.png" title="Editar" alt="Editar" height="25" width="25"></a>
                            <?php endif; ?>
                            <?php if($acl->isAllowed($role, $module, 'inativar')): ?>
                                <a href="javascript:void(0)" class="botoes_acao" onclick="inativar(<?= $contratopenalidade->getId() ?>, '<?= $contratopenalidade->getNumeroProcesso() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/desativar.png" title="Desativar" alt="Desativar" height="25" width="25"></a>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if($acl->isAllowed($role, $module, 'excluir')): ?>
                            <a href="javascript:void(0)" class="botoes_acao" onclick="excluir(<?= $contratopenalidade->getId() ?>, '<?= $contratopenalidade->getNumeroProcesso() ?>');"><img src="<?= $infra->getDiretorioGlobalImagens(); ?>/sistema/excluir.png" title="Excluir" alt="Excluir" height="25" width="25"></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<!--  Modal Cadastro -->
<div id="modalCadastro" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalCadastro" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-70">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="confirmaCancelar('modalCadastro');">×</button>
                <h5 class="modal-title" id="modalCadastro">Dados da Penalidade do Contrato</h5>
            </div>
            <form id="formCadastro">
                <input type="hidden" id="token" name="<?= $token['tokenKey'] ?>" value="<?= $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a id="primeira-aba" href="#tab_penalidade" data-toggle="tab" aria-expanded="true" class="nav-link active">
                                Penalidade
                            </a>
                        </li>
                        <li class="nav-item">
                            <a id="tab-movimento" href="#tab_movimento" data-toggle="tab" aria-expanded="false" class="nav-link disabled">
                                Movimentações
                            </a>
                        </li>
                        <li class="nav-item">
                            <a id="tab-anexo" href="#tab_anexo" data-toggle="tab" aria-expanded="false" class="nav-link disabled">
                                Anexos
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab_penalidade">
                            <div class="form-row">
                                <div class="col-12">
                                    <div class="form-row">
                                        <input type="hidden" id="id_usuario" name="id_usuario" value="<?= $id_usuario ?>">
                                        <div class="form-group col-md-3">
                                            <label for="lid_contrato">Contrato <span class="required">*</span></label>
                                            <?= $this->tag->textField(["lid_contrato", "class" => "form-control", "id" => "lid_contrato", "placeholder" => "Contrato", "onkeyup" => "autocompletarContrato('lid_contrato','id_contrato');"]) ?>
                                            <?= $this->tag->hiddenField(["id_contrato", "class" => "form-control", "id" => "id_contrato"]) ?>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label for="id_servico">Tipo de Serviço <span class="required">*</span></label>
                                            <?= $this->tag->select(['id_servico', $tipos_servicos, 'class' => 'form-control selectpicker', 'id' => 'id_servico', 'data-live-search' => true, 'data-style' => 'btn-light',
                                                'using' => ['id', 'descricao',],
                                                'useEmpty' => true,
                                                'emptyText' => 'Selecione o Tipo de Serviço',
                                                'emptyValue' => ''])
                                            ?>
                                        </div>
                                        <div class="form-group col-md-3 botoes_forms_alinhamento inputs_ocultos">
                                            <label for="statusv">Status </label>
                                            <?= $this->tag->textField(["statusv", "class" => "form-control", "id" => "statusv", 'disabled' => 'disabled']) ?>
                                        </div>
                                        <div class="form-group col-md-3 botoes_forms_alinhamento inputs_ocultos">
                                            <label for="data_criacaov">Data da Criação </label>
                                            <?= $this->tag->textField(["data_criacaov", "class" => "form-control", "id" => "data_criacaov", "disabled" => "disabled"]) ?>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label for="numero_processo">Nº Processo <span class="required">*</span></label>
                                            <?= $this->tag->textField(["numero_processo", "class" => "form-control numero_documento_oficial", "id" => "numero_processo", "placeholder" => "Nº Processo"]) ?>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label for="numero_notificacao">Nº Notificação <span class="required">*</span></label>
                                            <?= $this->tag->textField(["numero_notificacao", "class" => "form-control numero_documento_oficial", "id" => "numero_notificacao", "placeholder" => "Nº Notificação"]) ?>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label for="numero_rt">Nº Relatório Técnico <span class="required">*</span></label>
                                            <?= $this->tag->textField(["numero_rt", "class" => "form-control", "id" => "numero_rt", "placeholder" => "Nº Relatório Técnico"]) ?>
                                        </div>
                                        <div class="form-group col-md-3">
                                            <label for="numero_oficio">Nº Ofício <span class="required">*</span></label>
                                            <?= $this->tag->textField(["numero_oficio", "class" => "form-control numero_documento_oficial", "id" => "numero_oficio", "placeholder" => "Nº Ofício"]) ?>
                                        </div>
                                        <div class="form-group col-md-3 botoes_forms_alinhamento inputs_ocultos">
                                            <label for="data_recebimento_oficio_notificacaov">Data de Recebimento do Ofício </label>
                                            <?= $this->tag->textField(["data_recebimento_oficio_notificacaov", "class" => "form-control", "id" => "data_recebimento_oficio_notificacaov", "disabled" => "disabled"]) ?>
                                        </div>
                                        <div class="form-group col-md-3 botoes_forms_alinhamento inputs_ocultos">
                                            <label for="data_prazo_respostav">Prazo de Resposta </label>
                                            <?= $this->tag->textField(["data_prazo_respostav", "class" => "form-control", "id" => "data_prazo_respostav", "disabled" => "disabled"]) ?>
                                        </div>
                                        <div class="form-group col-md-3 botoes_forms_alinhamento inputs_ocultos">
                                            <label for="data_apresentacao_defesav">Data de Apresentação da Defesa </label>
                                            <?= $this->tag->textField(["data_apresentacao_defesav", "class" => "form-control", "id" => "data_apresentacao_defesav", "disabled" => "disabled"]) ?>
                                        </div>
                                        <div class="form-group col-md-12">
                                            <label for="motivo_penalidade">Motivo da Penalidade <span class="required">*</span></label>
                                            <?php echo $this->tag->textArea(["motivo_penalidade", "style" => "resize: none", "maxlength" => 3000, "class" => "form-control maxlength-textarea", "id" => "motivo_penalidade", "placeholder" => "Motivo da Penalidade"]) ?>
                                        </div>
                                        <div class="form-group col-md-3 botoes_forms_alinhamento">
                                            <label for="numero_oficio_multa">Nº Ofício da Multa </label>
                                            <?= $this->tag->textField(["numero_oficio_multa", "class" => "form-control numero_documento_oficial", "id" => "numero_oficio_multa", "placeholder" => "Nº Ofício da MUlta"]) ?>
                                        </div>
                                        <div class="form-group col-md-3 botoes_forms_alinhamento">
                                            <label for="valor_multa">Valor da Multa </label>
                                            <?= $this->tag->textField(["valor_multa", "class" => "form-control valor_monetario_limpo", "id" => "valor_multa", "placeholder" => "Valor da Multa"]) ?>
                                        </div>
                                        <div class="form-group col-md-3 botoes_forms_alinhamento inputs_ocultos">
                                            <label for="data_recebimento_oficio_multav">Data de Recebimento do Ofício da Multa </label>
                                            <?= $this->tag->textField(["data_recebimento_oficio_multav", "class" => "form-control", "id" => "data_recebimento_oficio_multav", "disabled" => "disabled"]) ?>
                                        </div>
                                        <div class="form-group col-md-12 botoes_forms_alinhamento inputs_ocultos">
                                            <label for="parecerv">Parecer </label>
                                            <?php echo $this->tag->textArea(["parecerv", "style" => "resize: none", "maxlength" => 3000, "class" => "form-control maxlength-textarea", "id" => "parecerv", "disabled" => "disabled"]) ?>
                                        </div>
                                        <div class="form-group col-md-12 botoes_forms_alinhamento">
                                            <label for="observacao">Observação </label>
                                            <?php echo $this->tag->textArea(["observacao", "style" => "resize: none", "maxlength" => 3000, "class" => "form-control maxlength-textarea", "id" => "observacao", "placeholder" => "Observação"]) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="tab_movimento">
                            <table id="tabela_lista_movimento" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                <thead>
                                <tr>
                                    <th colspan="4" class="fonte-15">Lista de Movimentações</th>
                                </tr>
                                <tr>
                                    <th>Tipo Anexo</th>
                                    <th>Descrição</th>
                                    <th>Data de Inclusão</th>
                                    <th>Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane fade" id="tab_anexo">
                            <table id="tabela_lista_anexosv" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                <thead>
                                <tr>
                                    <th colspan="4" class="fonte-15">Lista de Anexos</th>
                                </tr>
                                <tr>
                                    <th width="25%">Tipo Anexo</th>
                                    <th width="35%">Descrição</th>
                                    <th width="25%">Data de Inclusão</th>
                                    <th width="15%">Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id" name="id" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="confirmaCancelar('modalCadastro');">Fechar</button>
                        <button id="salvarCadastro" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light" onclick="salvar();" value="">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--Modal de Movimento de Contrato-->
<div id="modalMovimento" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalMovimento" aria-hidden="true" style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-sg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" aria-hidden="true" onclick="confirmaCancelar('modalMovimento');">×</button>
                <h5 class="modal-title" id="modalMovimento">Movimentação de Penalidade</h5>
            </div>
            <form id="formMovimento">
                <input type="hidden" id="token_movimento" name="<?= $token['tokenKey'] ?>" value="<?= $token['tokenValue'] ?>"> <!-- CSRFToken Control -->
                <div class="modal-body">
                    <!--Corpo do Modal-->
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="id_tipo_movimento">Tipo de Movimento <span class="required">*</span></label>
                            <?= $this->tag->select(['id_tipo_movimento', $tipos_movimentos, 'class' => 'form-control selectpicker', 'id' => 'id_tipo_movimento', 'data-live-search' => true, 'data-style' => 'btn-light', 'onchange' => 'exibirBloco();',
                                'using' => ['valor', 'descricao',],
                                'useEmpty' => true,
                                'emptyText' => 'Selecione o Tipo de Movimento',
                                'emptyValue' => ''])
                            ?>
                        </div>
                    </div>
                    <div id="bloco-receber-oficio-notificacao" class="form-row bloco_oculto"><!-- Bloco Receber Ofício Notificação -->

                    </div>
                    <div id="bloco-receber-oficio-multa" class="form-row bloco_oculto"><!-- Bloco Receber Ofício Multa -->

                    </div>
                    <div id="bloco-parecer" class="form-row bloco_oculto"><!-- Bloco Parecer -->

                    </div>
                    <div id="bloco-executar" class="form-row bloco_oculto"><!-- Bloco Executar -->

                    </div>
                    <div id="bloco-cancela" class="form-row bloco_oculto"><!-- Bloco Cancelar -->

                    </div>
                    <div id="bloco-estornar" class="form-row bloco_oculto"><!-- Bloco Estornar -->

                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <input type="hidden" id="id_movimento" name="id_movimento" value=""><!-- Manter como hidden -->
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="confirmaCancelar('modalMovimento');">Fechar</button>
                        <button id="salvarMovimento" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light" onclick="salvarMovimento();" value="">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!--  Modal Upload de Anexos -->
<div id="modalAnexoArquivo" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalAnexoArquivo" aria-hidden="true"
     style="display: none;" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-65">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h5 class="modal-title" id="modalAnexoArquivo">Anexar arquivos a Penalidade.: <span id="identificador-anexado"></span></h5>
            </div>
            <form id="formAnexoArquivo" action="contrato_penalidade/subir" enctype="multipart/form-data" method="POST">
                <input type="hidden" id="id_contrato_penalidade" name="id_contrato_penalidade" value=""><!-- Manter como hidden -->
                <div class="modal-body">
                    <table id="tabela_lista_anexos" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%" style="display: none;">
                        <thead>
                        <tr>
                            <th colspan="4" class="fonte-15">Lista de Anexos</th>
                        </tr>
                        <tr>
                            <th width="25%">Tipo Anexo</th>
                            <th width="35%">Descrição</th>
                            <th width="25%">Data de Inclusão</th>
                            <th width="15%">Ações</th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                    <div class="form-row">
                        <button type="button" name="bt_inserir_anexo" id="bt_inserir_anexo" class="btn btn-info btn-rounded waves-light w-md" onclick="inserirAnexo();">Novo Anexo</button>
                    </div>
                    <div id="agrupamento-anexos">
                        <div class="form-row" style="margin-top: 20px;">
                            <div class="form-group col-md-3">
                                <label for="id_tipo_anexo">Tipo de Anexo <span class="required">*</span></label>
                                <?= $this->tag->select(["id_tipo_anexo[]", $tipos_anexos, "class" => "form-control selectpicker", "id" => "id_tipo_anexo", "data-live-search" => "true", "data-style" => "btn-light",
                                    "using" => ["id", "descricao",],
                                    "useEmpty" => true,
                                    "emptyText" => "Selecione o Tipo de Anexo",
                                    "emptyValue" => ""])
                                ?>
                            </div>
                            <div class="form-group col-md-3 botoes_forms_alinhamento">
                                <label for="descricao">Descrição </label>
                                <?= $this->tag->textField(["descricao[]", "size" => 200, "class" => "form-control", "id" => "descricao", "placeholder" => "Descrição"]) ?>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="anexo">Anexo <span class="required">*</span></label>
                                <?= $this->tag->fileField(["anexo", "class" => "filestyle", "id" => "anexo"]) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-group col-md-6">
                        <p class="texto_rodape">Os campos com <span class="required">*</span> são obrigatórios!</p>
                    </div>
                    <div class="form-group col-md-6 botoes_rodape">
                        <button type="button" class="btn btn-secondary btn-rounded waves-effect limpar_modal" onclick="limparModalAnexos();" data-dismiss="modal">Fechar</button>
                        <button id="salvarAnexoArquivo" type="submit" class="btn btn-primary btn-rounded waves-effect waves-light">Salvar</button>
                    </div>
                </div><!-- /.modal-footer -->
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->