<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Circuitos - Sistema de Gestão de Circuitos do Navega Pará</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
        <meta content="Coderthemes" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <!-- App favicon -->
        <link rel="shortcut icon" href="<?= DIR_STATICS ?>public/images/favicon.png">

        <!-- Custom box css -->
        <link href="<?= DIR_STATICS ?>public/plugins/custombox/css/custombox.min.css" rel="stylesheet">

        <!-- App css -->
        <link href="<?= DIR_STATICS ?>public/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="<?= DIR_STATICS ?>public/css/icons.css" rel="stylesheet" type="text/css" />
        <link href="<?= DIR_STATICS ?>public/css/metismenu.min.css" rel="stylesheet" type="text/css" />
        <link href="<?= DIR_STATICS ?>public/css/style.css" rel="stylesheet" type="text/css" />
        <link href="<?= DIR_STATICS ?>public/css/custom.css" rel="stylesheet" type="text/css" />

        <script src="<?= DIR_STATICS ?>public/js/modernizr.min.js"></script>

        <!-- DataTables -->
        <link href="<?= DIR_STATICS ?>public/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
        <link href="<?= DIR_STATICS ?>public/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
        <link href="<?= DIR_STATICS ?>public/plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
        <!-- Select -->
        <link href="<?= DIR_STATICS ?>public/plugins/datatables/select/css/select.bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="<?= DIR_STATICS ?>public/plugins/datatables/select/css/select.dataTables.min.css" rel="stylesheet" type="text/css" />
        <!-- Sweet Alert css -->
        <link href="<?= DIR_STATICS ?>public/plugins/sweet-alert/sweetalert2.min.css" rel="stylesheet" type="text/css" />

        <link rel="stylesheet" href="<?= DIR_STATICS ?>public/plugins/switchery/switchery.min.css" />



    </head>


    <body>

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
            <div class="topbar">

                <!-- LOGO -->
                <div class="topbar-left">
                    <a href="index.html" class="logo">
                        <span>
                            <img src="<?= DIR_STATICS ?>public/images/logo.png" alt="" height="50">
                        </span>
                        <i>
                            <img src="<?= DIR_STATICS ?>public/images/logo_sm.png" alt="" height="28">
                        </i>
                    </a>
                </div>

                <nav class="navbar-custom">

                    <ul class="list-unstyled topbar-right-menu float-right mb-0">

                        <li class="dropdown notification-list">
                            <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button"
                               aria-haspopup="false" aria-expanded="false">
                                <img src="<?= DIR_STATICS ?>public/images/users/avatar-1.jpg" alt="user" class="rounded-circle"> <span class="ml-1"><?php echo $user ?><i class="mdi mdi-chevron-down"></i> </span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                                <!-- item-->
                                <div class="dropdown-item noti-title">
                                    <h6 class="text-overflow m-0">Bem vindo!</h6>
                                </div>

                                <!-- item-->
                                <!--<a href="javascript:void(0);" class="dropdown-item notify-item">
                                    <i class="fi-head"></i> <span>Meus dados</span>
                                </a>-->
                                <!-- item-->
                                <?php echo $this->tag->linkTo(["session/logout", "<i class='fi-power'></i> <span> Sair </span>", "class" => "dropdown-item notify-item"]) ?>

                            </div>
                        </li>

                    </ul>

                    <ul class="list-inline menu-left mb-0">
                        <li class="float-left">
                            <button class="button-menu-mobile open-left waves-light waves-effect">
                                <i class="dripicons-menu"></i>
                            </button>
                        </li>
                    </ul>

                </nav>

            </div>
            <!-- Top Bar End -->


            <!-- ========== Left Sidebar Start ========== -->
            <div class="left side-menu">
                <div class="slimscroll-menu" id="remove-scroll">

                    <!--- Sidemenu -->
                    <div id="sidebar-menu">
                        <!-- Left Menu Start -->
                        <ul class="metismenu" id="side-menu">

                            <li><?php echo $this->tag->linkTo(["index", "<i class='fi-air-play'></i> <span> Dashboard </span>"]) ?></li>

                            <li>
                                <a href="javascript: void(0);"><i class="fi-layers"></i> <span> Cadastros </span> <span class="menu-arrow"></span></a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li><?php echo $this->tag->linkTo(["cliente", "Clientes"]) ?></li>
                                    <li><?php echo $this->tag->linkTo(["cliente_unidade", "Unidades de Clientes"]) ?></li>
                                    <li><?php echo $this->tag->linkTo(["fabricante", "Fabricantes"]) ?></li>
                                    <li><?php echo $this->tag->linkTo(["modelo", "Modelos"]) ?></li>
                                    <li><?php echo $this->tag->linkTo(["equipamento", "Equipamentos"]) ?></li>
                                </ul>
                            </li>

                            <li><?php echo $this->tag->linkTo(["circuitos", "<i class='fi-link'></i> <span> Circuitos Navega Pará </span>"]) ?></li>

                            <li><?php echo $this->tag->linkTo(["movimentos", "<i class='fi-repeat'></i> <span> Movimentos </span>"]) ?></li>

                            <li>
                                <a href="javascript: void(0);"><i class="fi-lock"></i> <span> Segurança </span> <span class="menu-arrow"></span></a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li><?php echo $this->tag->linkTo(["usuario", "Usuários"]) ?></li>
                                    <!--
                                    <li><?php echo $this->tag->linkTo(["", "Perfis"]) ?></li>
                                    <li><?php echo $this->tag->linkTo(["", "Permissões"]) ?></li> -->
                                </ul>
                            </li>

                            <li>
                                <a href="javascript: void(0);"><i class="fi-cog"></i> <span> Configuração </span> <span class="menu-arrow"></span></a>
                                <ul class="nav-second-level" aria-expanded="false">
                                    <li><?php echo $this->tag->linkTo(["empresa", "Configuração da Empresa"]) ?></li>
                                    <li><?php echo $this->tag->linkTo(["lov", "Lista de Valores"]) ?></li>
                                </ul>
                            </li>

                        </ul>

                    </div>
                    <!-- Sidebar -->
                    <div class="clearfix"></div>

                </div>
                <!-- Sidebar -left -->

            </div>
            <!-- Left Sidebar End -->



            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container-fluid">
                        <?php echo $this->getContent(); ?>
                    </div> 
                    <!-- container -->
                </div> <!-- content -->
                <footer class="footer text-right">
                    2018 - 2019 © Empresa de Tecnologia da Informação e Comunicação do Estado do Pará - PRODEPA
                </footer>
            </div>
            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->
        </div>
        <!-- END wrapper -->

        <!-- jQuery  -->
        <script src="<?= DIR_STATICS ?>public/js/jquery.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/jquery-validate/jquery.validate.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/popper.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/bootstrap.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/metisMenu.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/waves.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/jquery.slimscroll.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/waypoints/lib/jquery.waypoints.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/counterup/jquery.counterup.min.js"></script>

        <!-- Required datatable js -->
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/dataTables.bootstrap4.min.js"></script>
        <!-- Buttons examples -->
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/dataTables.buttons.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/buttons.bootstrap4.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/jszip.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/pdfmake.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/vfs_fonts.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/buttons.html5.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/buttons.print.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/select/js/dataTables.select.min.js"></script>
        <!-- Responsive examples -->
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/dataTables.responsive.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/datatables/responsive.bootstrap4.min.js"></script>
        
        <!-- Modal-Effect -->
        <script src="<?= DIR_STATICS ?>public/plugins/custombox/js/custombox.min.js"></script>
        <script src="<?= DIR_STATICS ?>public/plugins/custombox/js/legacy.min.js"></script>

        <!-- Módulos -->
        <?php $module = $this->router->getControllerName(); ?>
        <?php switch($module){
            case "index":?>
            <?php break;
            case "cliente":?>
                <script src="<?= DIR_STATICS ?>public/js/modulos/cliente.js"></script>
            <?php break;
            case "cliente_unidade":?>
                <script src="<?= DIR_STATICS ?>public/js/modulos/cliente_unidade.js"></script>
            <?php break;
            case "usuario":?>
                <script src="<?= DIR_STATICS ?>public/js/modulos/usuario.js"></script>
            <?php break;
            case "lov":?>
                <script src="<?= DIR_STATICS ?>public/js/modulos/lov.js"></script>
            <?php break;
            case "empresa":?>
                <script src="<?= DIR_STATICS ?>public/js/modulos/empresa.js"></script>
            <?php break;
            case "fabricante":?>
                <script src="<?= DIR_STATICS ?>public/js/modulos/fabricante.js"></script>
            <?php break;
        } ?>

        <!-- Plugins -->
        <script src="<?= DIR_STATICS ?>public/js/uteis/accounting.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/uteis/jquery.mask.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/uteis/maskMoney.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/uteis/multiselect.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/uteis/uteis.js"></script>

        <!-- Sweet Alert Js  -->
        <script src="<?= DIR_STATICS ?>public/plugins/sweet-alert/sweetalert2.min.js"></script>

        <script src="<?= DIR_STATICS ?>public/plugins/switchery/switchery.min.js"></script>

        <!-- App js -->
        <script src="<?= DIR_STATICS ?>public/js/jquery.core.js"></script>
        <script src="<?= DIR_STATICS ?>public/js/jquery.app.js"></script>

    </body>
</html>