<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title float-left">Gestão de Cidade Digital</h4>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item">
                    <?php echo $this->tag->linkTo(["index", "Dashboard"]) ?>
                </li>
                <li class="breadcrumb-item active">Cidade Digital</li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<div class="row center-block">
    <?php echo $this->getContent(); ?>
</div>