<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title float-left">Usuários</h4>
            <ol class="breadcrumb float-right">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item active">Usuários</li>
            </ol>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<div class="row center-block">
    <?php echo $this->getContent(); ?>
</div>